### ISSUE TITLE
VisualSoar: Syntax coloring fails on certain files

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#102]
_From [maz...@gmail.com](https://code.google.com/u/105958812082577664437/) on February 15, 2012 12:38:01_

What steps will reproduce the problem? 1. Open up Operator_Tie\elaborations
2. Look at all code below selection*compare*partial-failure-evaluation-better-than-failure What is the expected output? What do you see instead? Syntax-colored text.  Syntax-uncolored text.

_Original issue: http://code.google.com/p/soar/issues/detail?id=101_

**Comment by mazina** [comment]
Not maintaining visual soar any more.  Long live the Soar IDE.
