### ISSUE TITLE
Hash of RL template instantiations are (1) not voided on excise and (2) do not properly maintain symbol ref counts

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#105]
_From [nate.der...@gmail.com](https://code.google.com/u/105203827464787627414/) on February 19, 2012 13:42:39_

There are 2 problems, with nearly identical setup... What steps will reproduce the problem? 1. Source attached rules
2. 5 decisions (d 5)
3. Print RL rules (p -r)
4. Excise RL rules (excise -r)
5. 5 decisions (d 5)
6. Print RL rules (p -r) What is the expected output? What do you see instead? Expected: Same number of rules in steps 3 and step 6 (i.e. template instantiations are regenerated after excise)
Instead: No RL rules in step 6

Notes:
To improve performance when using RL templates, we keep a set of constant-maps for each template associated, where a constant map refers to a distinct instantiation (essentially a hash). When a new instantiation matches, we hash it and compare against this set and only add if it can be added to the set (see reinforcement_learing.cpp:538). However, when rules are excised, the hash is not removed from the set, and so future instantiations will not be recreated.

This issue will likely not come up much in practice (usually we add rules monotonically). However, during interactive debugging or forgetting of rules, this could be a nightmare.

To see problem #2, comment out the "syms" rule in the attached file, and redo the script above. The "syms" rule makes sure certain constants have sufficient ref counts to always stay valid (w.r.t. rete symbol hashing). By removing this rule, you cause the 0/1 symbols to be removed from the rete hash as soon as the RL rules are excised (step 4). Consequently, when the template rematches, the 0/1 symbols in working memory have new symbol hashes, and are thus allowed into the template hash set (thereby appearing to function as intended). The outcome here can be a "memory leak" at best (with performance penalty for pushing rule-duplication detection to rete), and a memory corruption at worse (if the instantiation-hash symbols are ever dereferenced). The fix here *should* be simple, just adding/removing symbol refs when adding/removing instantiation hashes to/from the template set.

**Attachment:** [foo.soar](http://code.google.com/p/soar/issues/detail?id=104)

_Original issue: http://code.google.com/p/soar/issues/detail?id=104_

**Comment by mazina** [comment]
Ran the agent and template instances were regenerated.  Does not seem to be an issue in 9.6.  I think we were able to stop using that constant map when we changed something else a year or two ago.
