### ISSUE TITLE
Highlighting in VisualSoar

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#108]
_From [reiter.s...@gmail.com](https://code.google.com/u/108019843238501376671/) on April 04, 2012 12:29:14_

What steps will reproduce the problem? 1. copy paste some fragment of name which ends with * in name of operator
2. input space after ^ and before name of attribute

**Attachment:** [soar-highlight.png](http://code.google.com/p/soar/issues/detail?id=107)

_Original issue: http://code.google.com/p/soar/issues/detail?id=107_

**Comment by mazina** [comment]
Visual Soar is no longer being maintained.  Long live the SoarIDE
