### ISSUE TITLE
max-chunks then init causes crash

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#109]
_From [baz...@gmail.com](https://code.google.com/u/107839205919487237576/) on April 16, 2012 16:53:53_

What steps will reproduce the problem? 1. reach max-chunks
2. init
3. --> crash
       "can't find instantiation to retract. can't recover"

Original report: http://winter.eecs.umich.edu/soarwiki/User_talk:Kcoulter

_Original issue: http://code.google.com/p/soar/issues/detail?id=108_

**Comment by mazina** [comment]
Long-standing issue and still exists.  My guess is that the instantiation that it wants to retract is the one that it would have created to support the result.  

I've actually seen this same error of not being able to find an instantiation to retract many times in the last year for different.  While they didn't involve max-chunks, they probably involved chunks that also failed for one reason or another.  They could be similar insofar as a rule was never added to give them support.

**Comment by mazina** [comment]
I looked at this briefly.  I couldn't figure out a solution, but here's what I learned.

Using the blocks-world-hierarchical agent with a max-chunk of 1:

- The instantiation that it couldn't find to retract was an instantiation of default*elaborate*state*io, which seems like a fairly innocuous rule.  
- Two instantiations of that rule existed that it was searching through.
- Both had token/wme's of null, which made it impossible to match against either.
- Those nulls apparently mean they were both pending retractions.
-  I tried removing the code that sets them to null to see what happens, and they still didn't match the token/wme it needed.  Apparently, they were not the instantiations it was looking for.
- I turned on some RETE debug trace messages, and it does look like there were three tentative assertions for that rule.  

I'm not sure what happened to that third one, but I think the next step would be to figure whether it was correctly added to that list of instantiations for that p-node or somehow removed.

**Comment by mazina** [comment]
All the weird stuff was caused by odd leftover code that appeared to try to eat an assertion later in the decision cycle for the aborted chunk.  It seems like they never got aborting to work, and that was part of an unsuccessful attempt to clean things up.  Otherwise, I'm not sure what the point of that code was since it was also halting soar at the same time.  

Anyway, we got rid of everything and did it much more simply.  You can now hit max chunks and it will just interrupt.  You can keep running, init, etc.
