### ISSUE TITLE
create new GDS tutorial

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#11]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:10:59_

Description From Bob Marinier 2006-01-26 10:00:31 (-) [reply]
It seems clear that one of the reasons people get burned by the GDS is 
because
they don't even know it exists, much less the constraints it places on good
programming practices.  This is because the only mention of it in the 
manual is
in an appendix, and there is no tutorial on it.

I think it would be a good idea to add a short tutorial on th GDS to the 
current
tutorials.  It could be based on a simple counting example to demonstrate 
the
potential pitfalls and how to debug problems when you run into them. Karen 
also
suggested doing something with the water-jug-look-ahead code, since it's a 
good
example of why one would want to create o-supported structures in substates 
and
how to properly do it.

It would be great if this tutorial was written in time for the Soar 
workshop,
since then we could give an advanced tutorial on it.

_Original issue: http://code.google.com/p/soar/issues/detail?id=8_

**Comment by mazina** [comment]
Moved to documentation requests
