### ISSUE TITLE
excise -t should not also perform init

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#113]
_From [joseph...@gmail.com](https://code.google.com/u/113587566993378695814/) on June 24, 2012 17:16:37_

Right now it seems like issuing an excise -t will also reinit the Soar agent, which is not the behavior specified in the command documentation wiki. We should remove the automatic init.

Furthermore, I also don't understand why excise -a should automatically perform an init either. To me these are two completely different operations. When users programmatically issue these commands from SML, they are not going to see the "Agent reinitialized" output, and they may not realize the init happened (which is what happened to me just now).

Just like we disabled the automatic switching to epsilon-greedy when rl is enabled to prevent things from happening behind the user's back, we should also prevent the automatic init after excise -t and excise -a.

_Original issue: http://code.google.com/p/soar/issues/detail?id=112_

**Comment by mazina** [comment]
Functionality separate in latest commits
