### ISSUE TITLE
'quit' command not working

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#117]

**Comment by garfieldnate** [comment]
The `exit` command seems to work in `cli` and `cli -s` under 9.3.4. The output of `cli <myfile.soar` is a little weird to me, though. If the file contains two Soar productions, then the output is

    Instantiating Soar.  (kernel in current thread (optimized) on port 0)

    % *
    % #*
    % *
    % #*
    %

The initial output with `cli -s myfile.soar` is the expected `**`.

**Comment by mazina** [comment]
Not bug.
