### ISSUE TITLE
VisualSoar: some control key shortcuts not working on Mac OS X

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#122]
_From [jthal...@gmail.com](https://code.google.com/u/118372770212863148417/) on November 14, 2012 09:19:19_

What steps will reproduce the problem? 1. open a project in visual soar
2. example: control-F for search What is the expected output? What do you see instead? I am expecting the shortcuts listed as ^X next to the menu items to do the corresponding function.
I think there might be some layers of keyboard processing that are intercepting these. Pressing the option key, aka "ALT" does produce a little underline underneath the window's menus. What version of the product are you using? On what operating system? VisualSoar 1.0 on Mac OS X 10.7.5 based on VisualSoar version 4.6.1 Please provide any additional information below. feature wish: additional keyboard shortcut for closing windows.

_Original issue: http://code.google.com/p/soar/issues/detail?id=121_

**Comment by mazina** [comment]
VisualSoar no longer maintained.  Long live Soar IDE.
