### ISSUE TITLE
properly fix watch 5 with --fullwmes workaround

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#14]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:19:10_

Description From Bob Marinier 2006-03-29 16:32:15 (-) [reply]
1) Start TestCLI
2) source toh
3) w 5
4) w --fullwmes
5) run

Around dc 2 we segfault with the following error message:

Internal Soar Error:  symbol_to_string called on bad symbol
Soar cannot recover from this error.
You will have to restart Soar to run an agent.
Data is still available for inspection, but may be corrupt.
If a log was open, it has been closed for safety.Internal Soar Error:  
symbol_to
_string called on bad symbol
Soar cannot recover from this error.
You will have to restart Soar to run an agent.
Data is still available for inspection, but may be corrupt.
If a log was open, it has been closed for safety.

Note that this was originally encountered in Java TankSoar so it's not 
specific
to TestCLI.

This works fine in 8.5.2.

_Original issue: http://code.google.com/p/soar/issues/detail?id=12_

**Comment by mazina** [comment]
Agent ran fine in 9.6.  Not sure if that old workaround in place, but nothing actionable.
