### ISSUE TITLE
SoarEditor dies on init with certain files/folders in eclipse project

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#142]
_From [maz...@gmail.com](https://code.google.com/u/105958812082577664437/) on June 08, 2013 19:54:57_

What steps will reproduce the problem? Hard to reproduce.  Some file or folder structure I accidentally had in a project with my agents caused the SoarEditor to stop working.  Telling eclipse to exclude all non-soar resources (a single folder in my case) from the project resource list or manually deleting/moving the files allowed the SoarEditor to work again.  When I have more time, I'll try to figure what about that folder caused the issue. What is the expected output? What do you see instead? SoarEditor will not open or display any .soar file.  Instead you will get the error "Problems occurred when invoking code from plug-in: "org.eclipse.jface"." and an empty tab will open with no title or content.  Just an X.  

Note that datamap editor and other SoarEditor functionality will still work. Please use labels and text to provide additional information. Occurs in this part of SoarEditor.java.  Some file is causing it to die on the line "if (member instanceof IFile && member.getFileExtension().equalsIgnoreCase("dm"))":

    private static ArrayList<IFile> findDatamaps(IResource input)
    {
        ArrayList<IFile> ret = new ArrayList<IFile>();
        IContainer parent = input.getParent();
        if (parent == null) return ret;
        try
        {
            for (IResource member : parent.members())
            {
                if (member instanceof IFile && member.getFileExtension().equalsIgnoreCase("dm"))
                {
                    ret.add((IFile) member);
                }
            }
        }

_Original issue: http://code.google.com/p/soar/issues/detail?id=142_

**Comment by bluechill** [comment]
@mazina should this still be in the Soar repo? SoarEditor isn't here...
