### ISSUE TITLE
sml.Agent.getDecisionCycleCounter() returns wrong value

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#145]
_From [bob.mari...@soartech.com](https://code.google.com/u/112017452463115290100/) on July 25, 2013 14:50:35_

sml.Agent.getDecisionCycleCounter() appears to be linked to the decision phase counter, not the decision cycle counter.

Specifically, sml::Agent::getDecisionCycleCounter() (in sml_ClientAgent.cpp) calls (via an sml::Connection) KernelXML::HandleGetRunState with sml_Names::kParamDecision (in sml_KernelSMLHandlers.cpp), which calls AgentSML::GetNumDecisionsExecuted() (in sml_AgentSML.cpp) which does:

uint64_t AgentSML::GetNumDecisionsExecuted()
{
  return m_agent->decision_phases_count;
}

The correct field to return is d_cycle_count.

_Original issue: http://code.google.com/p/soar/issues/detail?id=145_

**Comment by bluechill** [comment]
@marinier 

Is this still an issue?  It's still the same but the comment above it notes that:

//Number of decisions (operator selections/impasses) instead of full D_cycles

**Comment by marinier** [comment]
It's an issue in that the method name is wrong (or what it's reporting is
wrong). The comment may help explain what's actually happening, but that
doesn't make it right. But to my knowledge it is not currently causing a
problem for anyone. But someone else could be just as confused as I was at
some point, and waste a bunch of time (like I did) before realizing it's
just a bug.

**Comment by mazina** [comment]
There's a GetNumDecisionCyclesExecuted that returns decision cycles, and there's a GetNumPhases too.  I'm not sure what name would make things that much clearer, so I'll leave as is for now.

**Comment by marinier** [comment]
FWIW, the name that would make things clearer is getDecisionPhaseCounter().
