### ISSUE TITLE
Templates can crash Soar if a variable used for a numeric preferences matches an identifier instead of a number

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#149]
_From [maz...@gmail.com](https://code.google.com/u/105958812082577664437/) on December 10, 2013 13:30:51_

What steps will reproduce the problem? 1. Source productions below
2. Step once
3. Call "print" to print templates produced What is the expected output? What do you see instead? It should have printout out a warning at run-time when it matches wme's that cause it to try to create an illegal rule.  Instead, it seems to create something invalid and then dies when it tries to print that invalid rule out.

One possibly interesting thing to note is that the final template does not cause an issue (comment out the other two, and it doesn't crash) despite the fact that it matches the same wme's that the previous template did and produces the same RHS numeric preference.  Instead, it works fine and doesn't create whatever it is that is causing the crash.  This may point to something more than just trying to use an identifier as a numeric preference value.

```
sp {init
   (state <s> ^superstate nil)
-->
   (<s> ^test-id <tp> <tp2>)
   (<tp2> ^value <dummy1> <dummy2>)
}

sp {propose
   (state <s> ^superstate nil
              ^test-id)
-->
   (<s> ^operator <o> +)
}

sp {template-problem1
    :template
    (state <s> ^operator <o> +
               ^test-id <id>
               ^test-id {<> <id> <id2> })
    (<id> ^value <v>)
-->
    (<s> ^operator <o> = <v>)
}

sp {template-problem2
    :template
    (state <s> ^operator <o> +
               ^test-id <id>
               ^test-id {<> <id> <id2> })
    (<id> ^value <v>)
-->
    (<s> ^operator <o> = <id>)
}

sp {template-NOT-problem2
    :template
    (state <s> ^operator <o> +
               ^test-id <id>
               ^test-id {<> <id> <id2> })
-->
    (<s> ^operator <o> = <id>)
}
```

_Original issue: http://code.google.com/p/soar/issues/detail?id=149_

**Comment by bluechill** [comment]
This produces a hard crash on latest version of Soar.

**Comment by mazina** [comment]
It no longer crashes but does create some weird preferences:
```
soar % pref s1

Preferences for S1 ^operator:

acceptables:
  O1  + :I
  O2  + :I

numeric indifferents:
  O2  =D2  :I
  O2  =D1  :I
  O1  =D2  :I
  O1  =D1  :I
  O2  =T1  :I
  O2  =T2  :I
  O1  =T1  :I
  O1  =T2  :I

selection probabilities:
  O2  + =0. :I (
%)
  O1  + =0. :I (
%)
```
Seems just as bad if not worse.  So, changed variablization code ti detects a bad match and abort.  It now does correct behavior and does not create a template instance based on the match.
