### ISSUE TITLE
Tcl SWIG doesn't work with threaded Tcl builds (ActiveTcl 8.4.11.2 or later)

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#16]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:25:14_

Description From Bob Marinier 2006-05-09 16:48:45 (-) [reply]
Starting with ActiveTcl 8.4.11.2, all Tcl packages are built with threading
enabled (although the core itself is supposedly not built this way).  This 
seems
to cause some problems with FilterTcl, since events are coming in on a 
different
thread.

Uncommenting the calls to the Tcl threaded stuff in the SWIG file seems to
mostly fix the issues.  The remaining problem is that some callbacks 
(including
the one that FilterTcl uses) need to return information, but that 
information is
being generated from another thread, so we need to block until it is 
available.

_Original issue: http://code.google.com/p/soar/issues/detail?id=15_

**Comment by mazina** [comment]
Pre-TclSoarLib issue
