### ISSUE TITLE
CSharp SML Fails

### ISSUE THREAD

**Issue by bluechill** [SoarGroup/Soar#160]
CSharp SML does not compile on the only platform it's supported on, Windows.  See:

http://141.212.109.224:8080/job/Soar/ARCH=64,SCU=--scu,SLAVE=Windows-8.1-Laird2,VS=2013/97/console

Should we remove CSharp, update/fix it, or something else?

**Comment by garfieldnate** [comment]
I am getting a compile failure again with the development branch:

    build\Core\ClientSMLSWIG\CSharp\src\Agent_Info.cs(33,22): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for 'delete_Agent_Info'
    build\Core\ClientSMLSWIG\CSharp\src\Agent_Info.cs(43,18): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for
            'Agent_Info_soarAgentSML_set'
    build\Core\ClientSMLSWIG\CSharp\src\Agent_Info.cs(46,47): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for
            'Agent_Info_soarAgentSML_get'
    build\Core\ClientSMLSWIG\CSharp\src\Agent_Info.cs(52,41): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for 'new_Agent_Info'
    build\Core\ClientSMLSWIG\CSharp\src\cmp_str.cs(33,22): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for 'delete_cmp_str'
    build\Core\ClientSMLSWIG\CSharp\src\cmp_str.cs(42,27): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for 'cmp_str_compare'
    build\Core\ClientSMLSWIG\CSharp\src\cmp_str.cs(46,38): error CS0117:
            'sml.smlPINVOKE' does not contain a definition for 'new_cmp_str'
    scons: *** [build\Core\ClientSMLSWIG\CSharp\sml_csharp.dll] Error 1

**Comment by mazina** [comment]
Try deleting your build directory or atleast the ClientSMLSWIG directory.
I have noticed that scons doesn't cleap up the .cpp files that SWIG
generates, so sometimes those files reference things that were exported
from a previous build.
