### ISSUE TITLE
Smem -a assertion failed

### ISSUE THREAD

**Issue by bluechill** [SoarGroup/Soar#180]
soar % smem -a {(@A1 ^age 1 ^link @A0)}
Assertion failed: (return_val != err), function execute, file Core/SoarKernel/src/soar_db.h, line 179.
Abort trap: 6

SMem shouldn't treat @A0 as an lti (ie. a string constant) or it should give a better error than assertion failed.

**Comment by bluechill** [comment]
This now gracefully and silently fails.  If you look at what actually happens it looks like it changes @A0 to @A1 silently which is bad.  @scijones I believe you changed the add command last so...

**Comment by scijones** [comment]
So, for the example above, there is a crash, but for the following example

smem -a {(@A1 ^link @B0)}

it fails silently and makes the identifier @B1.

For smem -a {(@B1 ^link @B0)}, there is a crash.

Now, I could try to read into these examples how things should be working and what is required when doing a proper fix, but I'm tempted to just add a check for an identifier with a number of zero. Does anyone have an example of a similar crash that doesn't involve an identifier with a number of zero?

**Comment by mazina** [comment]
None of these example crash for me on the binary 9.4 release.  None of them add a B0, but they don't crash.  Am I missing something?

```
~/Soar/_By_Version/9.4.0/bin> cli
Instantiating Soar.  (kernel in current thread (optimized) on port 0)
Created agent 1 named soar. Attempting to source agent-specific init file: soar.soar...
Error: Error changing to settings/
Soar CLI in single agent mode.  Use create <agent-name> to create another agent.

soar % smem -a {(@A1 ^link @B0)}
Knowledge added to semantic memory.
soar % smem -p
========================================
            Semantic Memory
========================================
(@A1 ^link @B1 [+1.000])
(@B1 [+0.000])

-------------------------
~/Soar/_By_Version/9.4.0/bin> cli
Instantiating Soar.  (kernel in current thread (optimized) on port 0)
Created agent 1 named soar. Attempting to source agent-specific init file: soar.soar...
Soar CLI in single agent mode.  Use create <agent-name> to create another agent.

soar % smem -a {(@A1 ^link @B0)}
Knowledge added to semantic memory.
soar % smem -p
========================================
            Semantic Memory
========================================
(@A1 ^link @B1 [+1.000])
(@B1 [+0.000])

--------------------

Instantiating Soar.  (kernel in current thread (optimized) on port 0)
Created agent 1 named soar. Attempting to source agent-specific init file: soar.soar...
Soar CLI in single agent mode.  Use create <agent-name> to create another agent.

soar % smem -a {(@B1 ^link @B0)}
Knowledge added to semantic memory.
soar % smem -p
========================================
            Semantic Memory
========================================
(@B1 ^link @B1 [+1.000])
soar %
```

**Comment by mazina** [comment]
Resolved with new version of smem
