### ISSUE TITLE
Print pipes around symbols that look like identifiers when being printed from smem

### ISSUE THREAD

**Issue by justinnhli** [SoarGroup/Soar#187]
Continuing #158 and #185. The main problems seem to be:
- strings that look like identifiers (such as |@N1|) should be quoted, as should strings that contain spaces
- this applies to both values and attributes
- there should be code reuse with the lexer

This issue is more about code elegance than functionality, as 9589c4b88bf54a32eae5568c4e4100e20322812c already achieves all three, although in an ugly way.

**Comment by mazina** [comment]
Semantic memory and STIs now use the same code to make symbols rereadable.  Changed in commit 5a46c2c5f249f5aece0d62fc03acbbb61a0604f4
