### ISSUE TITLE
problem with instantion retraction causes TestSoarPerformance to crash

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#200]
Soar crashes via line 6697 of rete.cpp during TestSoarPerformance's execution of the test suite with learning turned on. Here's the output:

    ========================================
             TestSoarPerformance
    ========================================
    Usage: out\TestSoarPerformance.exe [default | <agent path>] [<numtrials>]

    Running agent test_agents/TestSoarPerformance.soar for 3 iterations.

    ***** Running suite with learning off *****

    ***** Trial 1 of 3 Begin *****
    ***** Trial 1 of 3 Complete *****

    ***** Trial 2 of 3 Begin *****
    ***** Trial 2 of 3 Complete *****

    ***** Trial 3 of 3 Begin *****
    ***** Trial 3 of 3 Complete *****
    ***** Running suite with learning on *****

    ***** Trial 1 of 3 Begin *****
    Assertion failed: false, file c:\workspace\soar\core\soarkernel\src/init_soar.cpp, line 95

And the `soarerr` file message:

    Internal error: can't find existing instantiation to retract

, which comes from line 6697 of rete.cpp.

**Comment by bluechill** [comment]
This no longer occurs.  Considering "fixed" for now.  If it's not please comment & reopen.
