### ISSUE TITLE
consolidate set commands

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#201]
There are several commands to change Soar run-time settings.  Rather than have each setting have its own command, we'd like to just have one like "set".  For example, instead of "max-chunks 15" and "print-depth-level 5", we would have a single command like "set max-chunks 15" and "set print-level 5".  

"set" is the obvious keyword to use, but it can't be used because it's a core Tcl command. Any other ideas on what to call this new, consolidated command? My only other idea is "soar-set" or maybe "set-soar".

**Comment by marinier** [comment]
In general I support having a consolidated command. But "set" is a bad
choice, because it conflicts with the tcl set command, and SoarTech uses
tcl embedded in Soar all the time.

Bob

**Comment by marinier** [comment]
I guess I should finish reading before I reply :) Maybe set-param?

**Comment by mazina** [comment]
Soar 9.6 eliminates a lot of these with a few new commands.
