### ISSUE TITLE
update gen_cli.sh and help files

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#203]
* The help files that are used by gen_cli.sh should be stored as HTML instead of markup; this will make them more usable on the new website, and will make conversion easier.
* gen_cli.sh needs to be updated to use files hosted on Github instead of in the old Google code SVN repo
* (possibly) gen_cli.sh should be updated to take into account macros that are used for remove commands from compilation; for example, if svs is not included in the compilation, the explanation would read "the svs command is not included in this build of Soar".

**Comment by bluechill** [comment]
Fixed.  We use markup for the commands which are converted to plain text and latex correctly.  No need for HTML now.
