### ISSUE TITLE
explain special handling of gp and sp in tokenizer.h

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#210]
What is the purpose of the special handling of `sp` and `gp` as final arguments to a TCL command in tokenizer.h?

https://github.com/SoarGroup/Soar/blob/development/Core/shared/tokenizer.h#L420

I sort of wonder if it is debugging code that got left in. The command is passed to the tokenizer callback and the result is ignored, though the documentation says that a false return from the callback should kill the tokenizer. I am editing that file and need to change some things, but don't know what to do with this part.

File author is labeled as @voigtjr (5 years ago; how's your memory?).

**Comment by mazina** [comment]
Guessing he's no longer wondering about that.

**Comment by garfieldnate** [comment]
Now that I see it again, I am curious, but not fixing this doesn't hurt anything.
