### ISSUE TITLE
How to use input-link and output-link for a robot?

### ISSUE THREAD

**Issue by saikishor** [SoarGroup/Soar#213]
I am new to this platform (beginner) and i am having a small doubt 
like in what way can we use input-link and output-link feature

for example : If i want to input my robot state to the SOAR how can i do that?
and after processing in what way should i give an output like walk, speak, respond etc.

please help me.

**Comment by scijones** [comment]
I recommend you look at the [SML Quick Start Guide](http://soar.eecs.umich.edu/articles/articles/soar-markup-language-sml/78-sml-quick-start-guide). You can use SML to write code that writes to the input link and reads from the output link. What you decide to read and write depends on your problem and the reasoning you want to enable. For simple line-following robots, we input the color of the ground and output the speed of left and right motors (using tank-style steering).

**Comment by saikishor** [comment]
Thank for the answer @scijones 
so for example if i chose AR.Drone as my robot and to input the state of the robot like landed, take-off etc.., or to give output to turn left 90 degrees or increase altitude 

so do i need to write SML file for such operation or is there anyway i can get them....

**Comment by saikishor** [comment]
Thank you @scijones with your guidance now i am able to give input and get output from SOAR
