### ISSUE TITLE
how to run SoarTextIO in linux?

### ISSUE THREAD

**Issue by saikishor** [SoarGroup/Soar#215]
How can we run SoarTextIO in linux for creating a link for input and output link. Please help me
Is there any .sh file to run in terminal or is it only for windows??

**Comment by garfieldnate** [comment]
SoarTextIO is hosted on a separate repository: https://github.com/SoarGroup. The README file points to build instructions here: http://soar.eecs.umich.edu/articles/articles/soar-markup-language-sml/79-how-to-compile-sml-clients. I do not use Linux normally, so I can't tell you from experience, but try the build instructions given there and see if it works.

**Comment by saikishor** [comment]
so you do you mean that SoarTextIO onnly works on Windows but not on Linux... @garfieldnate

**Comment by garfieldnate** [comment]
I fixed the link the SoarTextIO repository in my comment above.

It should work on Linux. Here are the build instructions:

It's fairly straightforward to compile an SML client program from a shell using g++ or clang++. Both compilers take the same arguments. Supposing you unpacked Soar into /home/user/SoarSuite, the compilation command should be:

    g++ -L/home/user/SoarSuite/bin -I/home/user/SoarSuite/bin/include SoarTextIO.cpp -lSoar 

-L specifies additional library search directories, -I specifies additional include search directories, and -l specifies libraries to link to. The linker automatically figures out that -lSoar refers to the file libSoar.so on Linux or libSoar.dylib on OSX.

Note that even though the linker can find the Soar shared library at link-time, the OS will still not know where it is at run-time (unless you use theRPATH feature). Therefore, you still need to set the environment variables LD_LIBRARY_PATH on Linux and DYLD_LIBRARY_PATH on OSX to/home/user/SoarSuite/bin when running your compiled program. More details can be found in BuildLibrarySearchPaths.

**Comment by saikishor** [comment]
Thanks but my problem when i run that command is:
g++ -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -I/home/saikishor/Domains-SoarTextIO/src SoarTextIO.cpp -lSoar 

g++: error: SoarTextIO.cpp: No such file or directory

**Comment by garfieldnate** [comment]
Try something like this:

    cd /home/sakishor/Domains-SoarTextIO/src
    g++ -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/include -lSoar SoarTextIO.cpp

**Comment by saikishor** [comment]
it worked compiling but again i got some error @garfieldnate 

SoarTextIO.cpp:16:25: fatal error: portability.h: No such file or directory
 #include <portability.h>
                         ^
compilation terminated.

**Comment by garfieldnate** [comment]
That should be in the include directory that comes with Soar. Look around in your Soar distribution folder for the header files, and use that with `-I` instead of the path I used.

**Comment by saikishor** [comment]
yes it is in the include folder
when i run this modified command
g++ -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/include -lSoar SoarTextIO.cpp

where i added bin before include then it got run displaying following : 
 -lSoar SoarTextIO.cpp
/tmp/ccOZLKgC.o: In function `SoarTextIO::~SoarTextIO()':
SoarTextIO.cpp:(.text+0x2b8): undefined reference to `sml::Kernel::Shutdown()'
/tmp/ccOZLKgC.o: In function `SoarTextIO::init()':
SoarTextIO.cpp:(.text+0x591): undefined reference to `sml::Agent::GetInputLink()'
SoarTextIO.cpp:(.text+0x5af): undefined reference to `sml::Agent::GetOutputLink()'
SoarTextIO.cpp:(.text+0x6a7): undefined reference to `sml::Kernel::RegisterForSystemEvent(sml::smlSystemEventId, void (*)(sml::smlSystemEventId, void*, sml::Kernel*), void*, bool)'
SoarTextIO.cpp:(.text+0x6d7): undefined reference to `sml::Kernel::RegisterForSystemEvent(sml::smlSystemEventId, void (*)(sml::smlSystemEventId, void*, sml::Kernel*), void*, bool)'
SoarTextIO.cpp:(.text+0x707): undefined reference to `sml::Kernel::RegisterForAgentEvent(sml::smlAgentEventId, void (*)(sml::smlAgentEventId, void*, sml::Agent*), void*, bool)'
SoarTextIO.cpp:(.text+0x737): undefined reference to `sml::Kernel::RegisterForAgentEvent(sml::smlAgentEventId, void (*)(sml::smlAgentEventId, void*, sml::Agent*), void*, bool)'
SoarTextIO.cpp:(.text+0x767): undefined reference to `sml::Agent::RegisterForRunEvent(sml::smlRunEventId, void (*)(sml::smlRunEventId, void*, sml::Agent*, sml::smlPhase), void*, bool)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::runner()':
SoarTextIO.cpp:(.text+0x8a3): undefined reference to `pthread_create'
/tmp/ccOZLKgC.o: In function `RunForever(void*)':
SoarTextIO.cpp:(.text+0x8cc): undefined reference to `sml::Kernel::IsSoarRunning()'
SoarTextIO.cpp:(.text+0x8f6): undefined reference to `sml::Kernel::RunAllAgentsForever(sml::smlRunStepSize)'
/tmp/ccOZLKgC.o: In function `MyRunEventHandler(sml::smlRunEventId, void*, sml::Agent*, sml::smlPhase)':
SoarTextIO.cpp:(.text+0x9f1): undefined reference to `sml::Kernel::StopAllAgents()'
SoarTextIO.cpp:(.text+0xa1a): undefined reference to `sml::Agent::GetNumberOutputLinkChanges()'
/tmp/ccOZLKgC.o: In function `SoarTextIO::WriteCycle(std::istream*)':
SoarTextIO.cpp:(.text+0xb7a): undefined reference to `sml::Sleep(int, int)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::CarryOutCommand(std::istream*)':
SoarTextIO.cpp:(.text+0x14fb): undefined reference to `sml::Agent::ExecuteCommandLine(char const*, bool, bool)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::RespondCycle()':
SoarTextIO.cpp:(.text+0x2423): undefined reference to `sml::Agent::GetNumberCommands()'
SoarTextIO.cpp:(.text+0x243c): undefined reference to `sml::Agent::GetNumberOutputLinkChanges()'
SoarTextIO.cpp:(.text+0x2466): undefined reference to `sml::Agent::IsOutputLinkChangeAdd(int)'
SoarTextIO.cpp:(.text+0x2495): undefined reference to `sml::Agent::GetOutputLinkChange(int)'
SoarTextIO.cpp:(.text+0x2616): undefined reference to `sml::Agent::GetCommand(int)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::ResetConnect()':
SoarTextIO.cpp:(.text+0x3b64): undefined reference to `sml::Kernel::CreateKernelInNewThread(int)'
SoarTextIO.cpp:(.text+0x3bf4): undefined reference to `sml::Kernel::CreateAgent(char const*)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::RemoteConnect()':
SoarTextIO.cpp:(.text+0x3caa): undefined reference to `sml::Kernel::CreateRemoteConnection(bool, char const*, int, bool)'
SoarTextIO.cpp:(.text+0x3d77): undefined reference to `sml::Kernel::CreateRemoteConnection(bool, char const*, int, bool)'
SoarTextIO.cpp:(.text+0x3df7): undefined reference to `sml::Kernel::GetNumberAgents()'
SoarTextIO.cpp:(.text+0x3e19): undefined reference to `sml::Kernel::GetAgentByIndex(int)'
SoarTextIO.cpp:(.text+0x3ec4): undefined reference to `sml::Kernel::GetAgent(char const*)'
SoarTextIO.cpp:(.text+0x3f16): undefined reference to `sml::Kernel::GetAgent(char const*)'
SoarTextIO.cpp:(.text+0x3f42): undefined reference to `sml::Kernel::IsAgentValid(sml::Agent*)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::KillKernel()':
SoarTextIO.cpp:(.text+0x4049): undefined reference to `sml::Kernel::Shutdown()'
/tmp/ccOZLKgC.o: In function `SoarTextIO::spawnDebugger()':
SoarTextIO.cpp:(.text+0x40c9): undefined reference to `sml::Kernel::GetAllConnectionInfo()'
SoarTextIO.cpp:(.text+0x4111): undefined reference to `sml::Kernel::CheckForIncomingCommands()'
SoarTextIO.cpp:(.text+0x412c): undefined reference to `sml::Sleep(int, int)'
SoarTextIO.cpp:(.text+0x413f): undefined reference to `sml::Kernel::GetAllConnectionInfo()'
SoarTextIO.cpp:(.text+0x4159): undefined reference to `sml::Kernel::GetAgentStatus(char const*)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::step()':
SoarTextIO.cpp:(.text+0x41b0): undefined reference to `sml::Kernel::RunAllAgents(int, sml::smlRunStepSize, sml::smlRunStepSize)'
/tmp/ccOZLKgC.o: In function `SoarTextIO::buffered_change_t::make_change(sml::Agent*)':
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x47): undefined reference to `sml::Agent::DestroyWME(sml::WMElement*)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0xfe): undefined reference to `sml::Agent::CreateIntWME(sml::Identifier*, char const*, long long)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x182): undefined reference to `sml::Agent::CreateIntWME(sml::Identifier*, char const*, long long)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x1fc): undefined reference to `sml::Agent::CreateStringWME(sml::Identifier*, char const*, char const*)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x264): undefined reference to `sml::Agent::CreateStringWME(sml::Identifier*, char const*, char const*)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x303): undefined reference to `sml::Agent::CreateFloatWME(sml::Identifier*, char const*, double)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x363): undefined reference to `sml::Agent::CreateFloatWME(sml::Identifier*, char const*, double)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x3cb): undefined reference to `sml::Agent::CreateIdWME(sml::Identifier*, char const*)'
SoarTextIO.cpp:(.text._ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE[_ZN10SoarTextIO17buffered_change_t11make_changeEPN3sml5AgentE]+0x41d): undefined reference to `sml::Agent::CreateIdWME(sml::Identifier*, char const*)'
collect2: error: ld returned 1 exit status

and finally again i ended up with error.

**Comment by bluechill** [comment]
How are you compiling Soar? Those errors seem like you don't have Soar SML compiled into your lib Soar.

**Comment by saikishor** [comment]
Hmm...
actually i  am new to this software and i have a need with this so i am trying...
can you help me?
how to do that??
Please.... @bluechill

**Comment by bluechill** [comment]
http://soar.eecs.umich.edu/articles/articles/building-soar/81-building-on-linux

**Comment by saikishor** [comment]
Thanks
when i run python scons/scons.py all in SoarSuite Folder i get the following one 

saikishor@sai-HP-ENVY-15:~/SoarSuite_9.4.0-Linux_64bit$ python scons/scons.py all
python: can't open file 'scons/scons.py': [Errno 2] No such file or directory

what to do??

**Comment by bluechill** [comment]
```
apt-get install scons
scons
```

**Comment by saikishor** [comment]
ok after i installed scons : when i try to run scons
saikishor@sai-HP-ENVY-15:~$ scons

scons: *** No SConstruct file found.
File "/usr/lib/scons/SCons/Script/Main.py", line 905, in _main

**Comment by bluechill** [comment]
Make sure you're in the Soar source directory...

**Comment by saikishor** [comment]
that also i tried doing @bluechill :

saikishor@sai-HP-ENVY-15:~/SoarSuite_9.4.0-Linux_64bit$ scons

scons: *** No SConstruct file found.
File "/usr/lib/scons/SCons/Script/Main.py", line 905, in _main
saikishor@sai-HP-ENVY-15:~/SoarSuite_9.4.0-Linux_64bit$ python scons/scons.py all
python: can't open file 'scons/scons.py': [Errno 2] No such file or directory

**Comment by bluechill** [comment]
That's the binary release which should have everything you need already. @bazald can probably tell you more about why the binary release isn't working on Linux for you.

**Comment by saikishor** [comment]
ok ok @bluechill  thanks for the help till now

**Comment by saikishor** [comment]
@bazald can you help me to clear my issue??
Please....

**Comment by bazald** [comment]
I don't think the binary release of Soar is suitable for compiling
additional modules. It doesn't even come with the headers you'd need. You
would have to grab the source from the Soar repository that perfectly
corresponds to the binary release in order to be able to build compatible
modules.

I suggest compiling Soar from scratch using the master branch hosted on
GitHub (https://github.com/SoarGroup/Soar) and linking against that instead.

Best,
Mitchell

On Tue, Apr 21, 2015 at 2:38 PM, SAI KISHOR KOTHAKOTA <
notifications@github.com> wrote:

> @bazald <https://github.com/bazald> can you help me to clear my issue??
> Please....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoarGroup/Soar/issues/215#issuecomment-94899328>.
>



-- 
Mitchell Keith Bloch (http://bazald.com)
Member of the Soar Group (http://sitemaker.umich.edu/soar)
Wolverine Soft Ex-President (http://wolverinesoft.org)

**Comment by saikishor** [comment]
After doing all you said from first and start building and then running that command i got the following error @bazald 

saikishor@sai-HP-ENVY-15:~/Domains-SoarTextIO/src$ g++ -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp -lSoar
/tmp/ccMdamkT.o: In function `SoarTextIO::runner()':
SoarTextIO.cpp:(.text+0x8a3): undefined reference to `pthread_create'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `pthread_mutex_trylock'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `pthread_mutexattr_settype'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlsym'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlerror'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `pthread_mutexattr_destroy'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `pthread_mutexattr_init'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlopen'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

**Comment by bazald** [comment]
I see I was mistaken. The headers are there.

Try this:

g++ -L../../SoarSuite_9.4.0-Linux_64bit/bin
-I../../SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp -ldl
-lpthread -lSoar -Wl,-rpath,../../SoarSuite_9.4.0-Linux_64bit/bin

On Tue, Apr 21, 2015 at 4:24 PM, SAI KISHOR KOTHAKOTA <
notifications@github.com> wrote:

> After doing all you said from first and start building and then running
> that command i got the following error @bazald <https://github.com/bazald>
>
> saikishor@sai-HP-ENVY-15:~/Domains-SoarTextIO/src$ g++
> -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin
> -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp
> -lSoar
> /tmp/ccMdamkT.o: In function SoarTextIO::runner()':
> SoarTextIO.cpp:(.text+0x8a3): undefined reference topthread_create'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference to pthread_mutex_trylock'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference topthread_mutexattr_settype'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference to dlsym'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference todlerror'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference to pthread_mutexattr_destroy'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference topthread_mutexattr_init'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference to dlopen'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference todlclose'
> collect2: error: ld returned 1 exit status
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoarGroup/Soar/issues/215#issuecomment-94929229>.
>



-- 
Mitchell Keith Bloch (http://bazald.com)
Member of the Soar Group (http://sitemaker.umich.edu/soar)
Wolverine Soft Ex-President (http://wolverinesoft.org)

**Comment by saikishor** [comment]
i got this error when i did that:

saikishor@sai-HP-ENVY-15:~/Domains-SoarTextIO/src$ g++ -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp -ldl -lpthread -lSoar -Wl,-rpath,/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlsym'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlerror'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlopen'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

**Comment by bazald** [comment]
Then I question the LSB compliance of your distro. Which Linux distro are
you building on? And do you have an "lsb" package installed?

On Tue, Apr 21, 2015 at 4:50 PM, SAI KISHOR KOTHAKOTA <
notifications@github.com> wrote:

> i got this error when i did that:
>
> saikishor@sai-HP-ENVY-15:~/Domains-SoarTextIO/src$ g++
> -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin
> -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp
> -ldl -lpthread -lSoar
> -Wl,-rpath,/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference to dlsym'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference todlerror'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference to dlopen'
> /home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined
> reference todlclose'
> collect2: error: ld returned 1 exit status
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoarGroup/Soar/issues/215#issuecomment-94937093>.
>



-- 
Mitchell Keith Bloch (http://bazald.com)
Member of the Soar Group (http://sitemaker.umich.edu/soar)
Wolverine Soft Ex-President (http://wolverinesoft.org)

**Comment by saikishor** [comment]
Hmm.. @bazald 
I am using Ubuntu 14.04.2 LTS
and yes i have lsb package installed...

**Comment by bazald** [comment]
Hmm.... Try this command with  -Wl,--no-as-needed added:

g++ -L../../SoarSuite_9.4.0-Linux_64bit/bin
-I../../SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp -ldl
-lpthread -lSoar -Wl,-rpath,../../SoarSuite_9.4.0-Linux_64bit/bin
-Wl,--no-as-needed

On Tue, Apr 21, 2015 at 5:06 PM, SAI KISHOR KOTHAKOTA <
notifications@github.com> wrote:

> Hmm.. @bazald <https://github.com/bazald>
> I am using Ubuntu 14.04.2 LTS
> and yes i have lsb package installed...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoarGroup/Soar/issues/215#issuecomment-94943626>.
>



-- 
Mitchell Keith Bloch (http://bazald.com)
Member of the Soar Group (http://sitemaker.umich.edu/soar)
Wolverine Soft Ex-President (http://wolverinesoft.org)

**Comment by saikishor** [comment]
This was the result i got

saikishor@sai-HP-ENVY-15:~/Domains-SoarTextIO/src$ g++ -L/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -I/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/include SoarTextIO.cpp -ldl -lpthread -lSoar -Wl,-rpath,/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin -Wl,--no-as-needed
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlsym'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlerror'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlopen'
/home/saikishor/SoarSuite_9.4.0-Linux_64bit/bin/libSoar.so: undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

**Comment by bazald** [comment]
Other than attempting to build Soar from source, I'm out of ideas. Sorry.

--
Mitchell Keith Bloch (http://bazald.com)
Member of the Soar Group (http://sitemaker.umich.edu/soar)
Wolverine Soft Ex-President (http://wolverinesoft.org)

**Comment by saikishor** [comment]
Hmm ok that's fine i will try my level best to clear that and post if i get a solution 
and i thank you guys a lot and lot for atleast helping till now.
thanks a lot...
