### ISSUE TITLE
SOAR giving out commands in different order

### ISSUE THREAD

**Issue by saikishor** [SoarGroup/Soar#218]
the connection between SOAR and ROS is established and i am not able to get the correct commands in order of which SOAR gave in SoarJavaDebugger and finally it is not able to solve the problem.
please help me

**Comment by mazina** [comment]
I would suggest looking through example code in the downloads.  There is
already an interface from python to Soar through SWIG.  If you look at the
downloads, you can find some projects and examples that use that.

**Comment by saikishor** [comment]
@mazina thank you for the info and using that the connection is established 
but now i am not able to get commands in an order and problem is not solving when connecting
any specific reason for that

**Comment by saikishor** [comment]
i made the connection and its working good thanks for assistance @mazina
