### ISSUE TITLE
Problem with the input link to SAOR

### ISSUE THREAD

**Issue by saikishor** [SoarGroup/Soar#220]
my problem with input link is:

i am able to input values to the soar and proceed with the decision iterations but what happens is that decisions are not taken appropriately.

For example: I am given a variable integer value as an input and its like if the value is 0, a condition should process and if that value is 1, another condition should process. I coded such a way and i looked into the code there is no logical error
what happens is that even the value changes to 1, the first condition is processing for some time and then after 2-3 iterations even it is 0 or 1, the second process is executed.

Can anyone please help me..

code link : http://pastebin.com/dgPJCMLf , where "diff" is a input variable in code.

**Comment by bluechill** [comment]
I believe this was solved on the mailing list, if it was not, comment here.
