### ISSUE TITLE
init-soar fails after running blocks-world-operator-subgoaling-RL

### ISSUE THREAD

**Issue by bazald** [SoarGroup/Soar#221]
After sourcing blocks-world-operator-subgoaling-RL/blocks-world-operator-subgoaling-RL.soar from https://github.com/SoarGroup/Agents and running it, init-soar subsequently fails. I attempted to bisect, but a lot of commits don't seem to build. The last good build was 90ecc66859c8aba15abb64cb810bd2996f3f787d and the first bad build that compiled for me was b0e31d77cf0c30dcb2e43f012fa7ad0f2183fcad.

The bisect output follows:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
18027749076e398893e38209b38041367f4ea0b6
81fff108c48c0bf255ffb64d4d687c13bdf639c5
3d3bb885b4f367839ab27f79245231cda1bd1230
bf83a1550c9fcec7a7e92d7ba9c9414c3b97e114
438b38de3f37a19f6d055d204adcd995c26b74b3
724293626483ace43d5a0bda935d4fcd9b7f7794
5cb6baa0de8c3711946add4c91c467ea779166fb
fc8344b8b925974b498cfe507b69f9ea7f76b384
177bedefe5873affad45b82c61b16b5c622c402b
569abf3596ce20676a88d27221fc0140d6bea251
16bcf87aab8f1c3afcdf64606102680287adeca3
af1e9520d502c2b344fd79415dd54d9e88635150
af9a0dd672854172d9ba4ee0a9cc43e1ac065269
afa7aa3638643564331aa779187de95c139faa48
25d824e56ea64735ea8add779ba51042d7722a47
986d03c185d3c4219d9303e04e3006babfb3b585
1b6f5cf0636312d6d8b8a66bba2579655115e006
4820b4ffdb221cd60f8701dd36254f133b523bf1
3445967d887b57e09a1d325f96e578cc8bfcdd89
93af834b1628a187a4253232a6e4a74dc2369645
0b23d70c33e3c78edd8803e2010ddbbf61e343c4
3177370dc3be95888841b246d926719ab87b1ffa
3e64ac2a4be6376775ff2ed578833cb47d7a9c76
402270370f429ed97b862bbe11208322460d6055
79f9ad70bbb56850cfe88ced7173b87662aaa5b5
963801941ffa084651a4e3a10112532600f201db
37e46462b805fbe0d0062ed37d8afd492b56e6e1
d6e06bc618a0f847ec5a673d937c7a97d387ff6c
93703db1e169738904e98c5d118dcdebd905d7e9
dd30ed588963e3aed6c44b64ef3bd9db64bca264
463f1a63c6882ec3b68c25d69446c3be23f17f03
f130fb4d050a66a29f3cf599f49e7217224a4e52
1cc42be80dcc540ebf1a3a4b63fe21bd97363cd9
c908c58d9a448cec388094fa648e71bf9b477382
bedabb56c7ad69c5a699464469f51078b67fa9d9
c9d542372e7d4f4626130294e6f660bd5b26fc22
09d459edbddf309c7fc552e17d6a336e997c4ef7
6828babbc08531666b6e0ee93ceda17c1ab85f4c
ab735885479f554e723b48696afa31851e949108
bc09d498fc30423845e8062d5e435d0c3fd6f6f6
3d7cccfdd55d6a49e52e24c13ea05ac62c77acab
93c0cbb7bfceea0bcced5497d5c459f044de016d
3a6c41bd046818a6bd3860100730ba0d25dcdf81
d7880574bf46afff76a6c3e143cf764486eece8c
46c061b672b679d3069b3ea9b0b528d2aefc8786
b8b5edca4029a6a6945650d6f2172eb2d8e5d6ad
c593cfcb5cbaaf3d4d9a925f68c37b661f891286
da3615a99b318b92e895565c19f99cec0421cc3a
7ce273417a4deabbe2916c02b3d1791a451335c8
8bf72cd649c9a58b733ac3d44d3adc82b0fe22c4
564151f8ff9237b8d7c54366fc6a1236497d8a77
aa356d43356821889cd7081a2dfcf5c2aa3fb864
09096dbbdf1c2e1abb5be98de5a5b0e8e565b97c
f99317bb85026becf25ad16aa2adbab15f1f801c
0521c802b4ea94f2fada3496426ed419a980f327
3e52d2050a890dfbb6502eb7bc804cd7a6f9f929
bf3549f0b6835bcd26f2e81aa1b8db5a368a2e25
bfdbddd88445bb1c4353cf3329bc55d01335c225
c4afbb5a1bd913c2a43b442e910412963c072ed6
e66df9f0d42246c52d383e8dbeb6f56d60c36617
bbd053c247f8e081deeac3a48946dea0ef131da5
cd0c09faea8affce836c648d07a1864eef5d9a6c
1cff3194673afdf653e7ce61f904d354bcbf4031
32b5864c40ef564b6605c38d3178d23383863091
878d109d186e2ad48f531a88ecb7bec15622ef5d
e51c61302ed5dd0e9746f2f31bc51d4e9a834aa7
157e5f1b604c965ea749cdf9894c07e6fcd3c1b5
4e2a18d8f7884e65a994c1ab46b9f2c202be85f6
7e626a000cfb4b03e222567b1754868668895945
df7304d31969f0e653211ce75d09088b1dee697d
6790644e7f51650befd7be924b0d262c1bbf1a01
f0365483d6ce59220ebe4e6675bd8d993e6cba3f
1b2b2503b62fc22522828c5755d37dbb88a68185
f5b12baa0e43856b35754477acb45d0aab3e3f3f
8f3b59bc04a617791f1ce9b2519a1997d3e1de3c
df21ff6463343192f6b27dc751baa26447df32ce
3baea672a016bcbc406675c240ccfec17b3d08df
a8be034bd2ccabe86551ceccecd0de069ea22b03
97c7a5cb454073ff43001f4543b6dccc51bbdb33
be6930120e797e72a2ce1fe03a3ed4a46de985ce
7c2c77bca4901e5d640b050d00155b388d8c4f6e
b269c240c3148102a4964388632f2adce741a6aa
a2d9b9aae22a6dbe80e02ca2d00419bfe0b21a8a
e18949107e5a6c0d25b06d59ba5ff07cbe2e9016
1cfd15446cf55a78d8e51afd59e1338d395d0d38
dce50b369a7d761df75142fd8fde3f085742b820
5f9dd2db7db05912092e75923df4d9363a2d4953
7211ba4c22c189508b114f7f99c71e7b8bd6ea84
c71e34b3ab63aaf95fa59fdc49a73acafb0ff917
de0d37fd3ae22406e2fd728e19524039fcade2bd
4162b1ed9f260917ce8008e9b75e3d3d1ac22fb6
a950e8a4dea3cd06d3c73cc5bba9aeea4e8eb018
a01f79e44295357628b54066db3c090c28e3d0d3
c303fe6f62c1e79d4187491ae91655f891d7e255
254efe9b97a4dc2590dfba04be65b8ba3f672e60
6da716657503869bf6156b234e65720cf00347ea
0b955635cccc67055c4f185ff84d66c4df6e2e52
5909195f0908d16ba3d4dd1f425333f6973183c4
3e38abc3ff7701737cd982961f748165591d24da
af7809de85a75969de80111e41bbce232dd3618d
21003b4a7429b415733a9c09e00296eb15dcdf7b
c9761c3fd20eef2e418034a9aece09b14845c1c5
5ebd6a54be5a174ba82712cabf61fccfbc658a50
a97774d6b1a3d3406f6e24ed8a71c095796dc911
63f7cbf4f85cefa8d5c872311b047fd9ba6a1376
9d356fc77af1fca40d7df00c9a7c2eb32894d6d2
0c46b86d211f66f0cbbe6e8d816df22e28f43bca
7d8c451dcef512156c8c96f661eed50c4d5b2aa0
186120bfa6109ae98e955379b8786b2d76f87004
c4162ee69fec6d7d73000f2272f8d71a5996f28c
4a9b00036a36f5900319f2140e9ea7e939a448c6
cd51c834e31222d37c5942767fdf4c40cfe2d56d
82bcce5319e72b5c2daa516fb71a3540a7af6a07
a45dcc2bd182105f1033778162a62383ae6010db
6d02450cabdebfb9c193fe5536ddb3b35dafce16
c81bd2911ef5e6988f89e083a2ffc6aa002e080e
11f3e8be2f47f6ff536e05870f16a72cdc2926ff
a404ea56d71309426b52a96752a741ec9b05eb7f
4e28e11ecbe94e1a7c46e51394167bcc06480512
b89d509fc1bdf1cf61148015fea4ff84b8fbb6e5
09393339af3daec2f1201a75894b230f0884638e
7b827089196ab7e96016c93f7a3d020e9ad06068
086d4026dd33d19bc4fe53936138d038c2b1ebcb
dbf5be172fb2774cd8c9ea9e4429bf93c454e3e1
9036f5bc957f04554c44b06335d41a628e9b3aca
dc5755420132a3b836e5372f4dc2337c59db5a89
91b5a6e6cfc3490b169e11029c0b5a0c9fda0759
f691cdff4eb9456e2a52d7b67b8284f3cfc44a42
3541d33578b4c6477b6d7a4c40f205b02b98bd7e
7eb6b0cdbcb98fd36220332de678f4c3b9b9bf84
3c76535fc3c259d16936e02954269a55c79bd440
7841a351ed2c51afaf4e028cf26ed0827fa21251
34f9b1e7cd9e7c17fa295269ed0594cbd5fc33b3
95b77bcc8adea4200f52167672445e21bab52ca1
a52bc46f2c68bbb0fc124baa193ab40094dea573
fb40f57632969143a4dc2f59eb3fdfece4bdea56
63b1dabf9cfcfc2dbafffe62a65d413187cf1edb
7022f5f37697eb75ffcc47936cb631f65d44c290
9a4fce954aa25b106afa13895fafca969398e8a0
de0294f6e54c26213cfc4ce911f742394ac78dc6
5e6814002fb1ea317ce97416f9ee5589eacaca34
73cb7aaef3029c406929377beff2ecd0d3f34e45
56609bb2aa8b0e17860eb6228c42527ffccf24f5
8d4dd06d220a341081533f2ff811998f9a8205b8
0d577219d76f5a863e363bc0e85fe9900cd10d57
7a76d1ca246afa1cb41b8ab37be5da5a6ed1328c
6c8231577d63aa7bebe8ffe85eabeaf0ada08908
82c439b98bfdde0b41c16f0afcd70eab9e04f97e
1a9806f365a728513b5074fc09739c9e4a8ef8fc
6f115f0901a7cc89b98fca3405bfe2566b9932c4
45f9d387f59f5f52dc618052ed2fb96fd4dbe898
5f1a86077212a70b50f899a378343864529f3ab7
0477ff51770095f0f419754ba3038137a57db15d
673902dc9f77ed07e43ed934a49a90062422f3ae
a31853bbd0bb0f5b58a1caab6f343d746d17205b
a6c7e4f1a347526244dc070fe127eaebff978448
3e4116ada028a7ff300d7355e8ff1a3dc5edc2b1
b524c0b203c1b33259f6f504559000e7ec6a6a4e
783e2687a4da088af06a2f1ed0c4a4852399fd7f
eb83c8fa92036df108c13d2dfc5e90ae3e6f7703
bc86fd81fd2de14cbbeaf435820a89e9ee93515a
c084ea9b3f49397139b7f74fb6782cdbb9083506
06af8d9864bc4f0c2385cbd54b9bf7db0a26e04a
0913565d66be5cbcfc14f694b3af56f4b52ec33b
7ccbafc485371335f18c2677dc175d70325ef2a1
a6fae14d8690a119ebca2d0106aae6d7800b49da
9c0d7aaccfe4faade1a622784f9941eb042b8832
dcd8ddc3de5ef1fa610b8d1a21864b0f94b599c7
210f3cc9b0121b79240d3e826ca6ae2b5b6dd07e
968bb5c35008f652b2cf6ce780939b8710cafa01
36f754856ca70b059024a0feb273fe23080a212d
f487be52eb9a23556a79d1ad5d5f8ce03b4f4f4b
1d5de5c9a18ada2ff82a821f9006e4b9ade328d1
67d787e2484870ddeb8ac369f1bbef013178b0c3
6ae23ec7fb97626a432b9057cbbe3e61690a2bd3
b2450337864eb48f59a7dc7bab05e9d09882bd3d
29d2ac3b7d20f51c0bb4cead461eb7e22ffe1cb5
6040e88b48b1d1d216c258f6a1fdcaa33aae4d99
a54604bf4ade1f6314fafaf956afb04939a77df9
b53d71ca745a7538c2458861f5904530ed62e0c2
92334d88c3a9bc11288d393daa0b833143c2a58c
939498b66af301e2f5fee380c917ee5bc8b531c9
751e6312fe0e8391a36e7580906eb6937b964cb1
d5b134ee576f461a5e2acb7d3b1b1177749061c4
4525fac49ab8d0e8c5963d2f24e492aaeae05405
aaa7c027de4e6fc5ff6e8e1ee930e0f0ab2610e8
3330779ce11a45b1ad9364906a06f6c3f5409004
d7292069005c9b7d90277aaecb2d7cc2b8b69685
91efe471df0a0625807ed5acb965cc3b428b1535
ea8bb0bd311d3aea6137e081873406c765df7684
068d26d6e9ebc93bd99d1565aa7f39fa7e88f149
74f68b7668575773aa38e6499867cc4b5c66d32b
9b312436693954f6d234d2b6cbf0735b60bfd5fd
dde6c342e7d1ffb11847507b3c41fb1f022e324a
f3a96ffbd39e1fe731c52c7a7d6f63b5933b1be1
ffce2a48c9c52b3fce0eb654340f4cd6468eb749
099a6099ed3922bc01794e4fec3b0883dcdc6c8f
6a54f3582aa56c755d4014fc3290d3df613b2c7e
8ec9eb8ca22c597c346fde928ed6e0b4568fc773
bfd789bb52198f0490fd210204165a9db71d8229
17594ad90363930739bc460912b24d9d1d21a8cf
c12a21cb671dd39d9d2ef3938c18233e1affed0d
235a5122fc0b5540f391891561d3f5110654953d
3439abccf6ec85d40576ab0fae7f5fef0c6e46cc
c4da546b0df07c5dc9a8df31388214e7d46ac000
ee5493478c729c4c84ebf3ede9f0e5bbb5869516
3a7726b6c6f40c08825ee4392324f36656203f6a
db7f122729e645f93a8b2ecdbc503283f78bd4d3
1f2ef877414aa21d58f4f72bddc8dbf365d3e659
bef45a520c371675c1c8b9c56c4bdf857d52e3aa
f25ac0234b7f529c5e7071315301e1ac0f5e6ea0
f86b3306328ccd7447460a9933068f0a1bdb9830
6eae09529cd0367ac3ce7f9f1f8f389ba38f6708
97f539075eb03e97fd5dfa83cc0d1039c1ef628d
bb266458e564ac550aef355113b23c7b9deb5d3f
f03868093da31006ea2b89dced5c1ff671515014
22afce2c6e4d6f19996674e2790e3399a6bc488a
91009a292dff4030ce079a602009e96c20799f59
7fe82f18bb575bed6d525a71aa50f5c9360ff0b1
84e03c590c4f9fab9382fefd5b6ac9831b8b44c6
42441d2e7ba813acf49beda00b76110fbce60f6c
4dff224a41b9e625ac67f358486c34b779988110
1abdbddf56c3eac48a5eb3b47dc08f118e3b5fd8
e1136992bc22704b267991ee4e0120a3ba648e88
413d1df797f1687c42c01bb6e0e368449e891bec
babddc2ebb315160721986c36ddc62a1007b2c1a
03d0078e189d0db5e2a9b48d06e9048ab5fc967f
98895595941cc1d68427981edba502bb051a709f
55b4cbaca8e37399ada7acb5f70122b3c651458d
5a3cadce894a43d70542a5c314776e1f41bc67e3
39ee7ec585d3db27d8a9f02101885c40f1b2ed22
d0935bcdadf8ee86c8d55c51f63f459e12975392
39a34593a50b43b90e3baafea7f078f518812990
e1c09ac5abf7fad22543ad2f0a744ac2ff0e8f09
62a0677d1e0c8036a051645eef07fb9972b5b0dd
b3fb6d0aceb3b65fdf4406912b7d5ae29238d38c
8df5b7b8e242802db3e246ada46155b507d9fb16
90b99e00e8d1692dc8b42b6db17aafe07690171a
61045bdac4f54de9f27f201eca7305118539c2f1
ac0ba2eab9d78d569e010c5c048201d52f618c90
993a1c9945178828243e5f447ea94a58406797c6
a2863aad5ad808e625f783695a1e71bd20e07af2
1a3bfd841a1d2c46e5ace18b1b5263d5c7c37442
478ffda84262feae3591e534c33ab2ccba067f9c
125d558282d1ec14fdc041fbb59a58162fa1f8ed
2eda4b362e4a48e3dcb07a2d0383f0bdb72ca797
2dc8d06459ebc92aa7827f9e5bdc0ef628c4549f
8d47922098212a30febbd9178a4c1db1965fcc19
27928bb87688da5bac13a5f60e95a804551e92c8
d20e9f85d941e1f90df9f92dc00c9f29e6045484
032a22c81b854bcafb2246c41b0fe5843efa2a70
e710b9d5a836c292b2506e029b28711a06436e87
c4cb1681418e2c62baaa6bdfb4b0d1ac42034667
d6ce30ba081091e36976a2288165458cc727dfa7
1029ca0c87762070cd42871f157d1661b03a527e
47dd5b239be5f5e8ecf19c9c0bcbb955063c0d43
7a54a6cb9250797ff1c96cb3f8d4dee3078349f9
be2f46c2d9ed27128ff33f6c6ef51ea82f1fdc45
08268a4770fce2e48f69d9982ebb0787986b0b79
9e806d42511ba3a595986f460258e04036627a22
541e06129a1521409b71c8b89a8ef4fe6d673274
f28452dd4d3adf69791ab827aa4c8816bf1f1816
39f4f2054f28925493808a8868b3396dffbce667
f5020e89ea5b73fe45e9c42a9cc089ac966a5e75
53afba028002bdc989fd8822f0a85e39e68e2612
67e1deab1cc72101d2243465c8597a341d71a5f0
a628f80f943082c3d5607c7e295f6fecfefd01c2
ca050ce27ca84892ea097b1c6c709c42c5e8509a
034f68a492a958b5e21fc7e46a3604c21fcbc062
3c176b437a123e6f07117955bd5e3e72344aba8a
206a5fdfde01c97faf99023182f05b7f0a209515
c481c9287a238dbfe16e6a40745d331a04d2e0dd
b0e31d77cf0c30dcb2e43f012fa7ad0f2183fcad

**Comment by mazina** [comment]
Haha, so the last good build was 2 years ago before it all started and the
first bad build was 16 months later lol.

I'm assuming it won't init because identifiers are leaking? I'll add it to
the list. Do any rl agents work without leaking?

**Comment by bazald** [comment]
blocks-world-RL and water-jug-rl seem capable of reiniting just fine. Therefore, I'd assume it has something to do with the operator-subgoaling indicated in the name of the agent.

My system seemed to be unable to compile anything between the good and bad revisions that I fingered. If there's something I'm missing that's required to get them to compile correctly, if you can tell me, I can redo the bisect for that range.

**Comment by mazina** [comment]
I'm not sure why none of those in that huge span compile at all for you,
but my guess is that 8-month point when it does start compiling for you is
when my 9.5 non-github repo was painfully migrated over and merged into
branch off of our github repo. And maybe the two year mark when it stopped
compiling was when I originally branched off of Soar 9.3.2 from SVN into my
own git repo.

Anyway, there's no point in figuring the bisect out.  The last few months,
and the last month in particular, have seen a serious re-factoring and
clean-up of the code.  And I'm guessing this problem is something more
fundamental having to do with the change in variablization, which RL uses,
and not something that could be tracked down to an incremental change in a
particular commit.

I'll look into those agents.

**Comment by bazald** [comment]
Ironically, I have no idea how to evaluate blocks-world-operator-subgoaling-RL after all, but I can confirm that commit 3b53175487fc8532c3b43770774d09b518b839aa fixes the bug. Closed.
