### ISSUE TITLE
SoarJavaDebugger is 20x slower on Mac/Linux

### ISSUE THREAD

**Issue by natederbinsky** [SoarGroup/Soar#222]
To replicate:
1. Start the SoarJavaDebugger
2. Load the arithmetic agent
3. `srand <something>`
4. `w 0`
5. Turn off all traces (to avoid time lost to printing)
6. `time d 10000`

On my Mac (OS X 10.10.3), approximate time is 24s. Running a 64-bit Ubuntu 14.04 VM on the same machine takes about the same time. HOWEVER, running a Windows 7 VM on the same computer takes about 1s. By comparison, the run takes about 1s using the `cli` on all three platforms (i.e. Soar itself runs fine on all three platform).

The `stats` for Mac/Linux report most time going to Output phase. Note that the agent does not enable any learning mechanisms.

I only used the 9.4.0 tutorial package (64-bit) for all three tests, but I feel like at least Mac has been slow for as long as I can remember.

**Comment by bluechill** [comment]
Just checking, is it an optimized build?

**Comment by bluechill** [comment]
Actually that "9.4.0 tutorial package" implies its an optimized build but it could be a mistake in compiling it.  Comparing the master definitively compiled as optimized vs windows would be a thing to check.

Because:

```
source {/Users/bluechill/Developer/SoarGroupProjects/Soar/master/Tests/Agents/arithmetic/arithmetic.soar}
learning = on
Knowledge added to semantic memory.
Knowledge added to semantic memory.
Knowledge added to semantic memory.
*****
*
***************
**
*****
***
**
**
*****
*
**
***
***
***
**
**
**
*
***
**
************
*
****
**
*
***
*
*
***
**
***
**
Total: 99 productions sourced.
srand 1231231231
w 0
watch --level 0
time d 10000

(0.610468s) real
stats
Soar 9.4.0 on Alexs-MacBook-Pro.local at Sun May 31 22:22:44 2015

99 productions (0 default, 99 user, 0 chunks)
   + 0 justifications
                                                        |   Computed
Phases:      Input   Propose   Decide   Apply    Output |     Totals
========================================================|===========
Kernel:      0.000    0.004    0.041    0.184    0.112  |      0.341
========================================================|===========
Input fn:    0.000                                      |      0.000
========================================================|===========
Outpt fn:                                        0.000  |      0.000
========================================================|===========
Callbcks:    0.000    0.000    0.000    0.000    0.000  |      0.000
========================================================|===========
Computed------------------------------------------------+-----------
Totals:      0.000    0.004    0.041    0.184    0.113  |      0.341

Values from single timers:
 Kernel CPU Time:       0.356 sec. 
 Total  CPU Time:       0.365 sec.

10000 decisions (0.036 msec/decision)
23546 elaboration cycles (2.355 ec's per dc, 0.015 msec/ec)
26753 inner elaboration cycles
7675 p-elaboration cycles (0.767 pe's per dc, 0.046 msec/pe)
38717 production firings (1.644 pf's per ec, 0.009 msec/pf)
276841 wme changes (138459 additions, 138382 removals)
WM size: 77 current, 78.494 mean, 180 maximum
```

**Comment by natederbinsky** [comment]
The absolute time isn't important. What is troubling is the comparison between SoarJavaDebugger vs. cli (or choose a simple SML program of your choice/programming). On Windows there is basically no difference, but on Mac/Linux there is a 20x difference.

**Comment by bluechill** [comment]
Optimized build:

```
% source /Users/bluechill/Developer/SoarGroupProjects/Soar/master/Tests/Agents/arithmetic/arithmetic.soar
learning = on
Knowledge added to semantic memory.
Knowledge added to semantic memory.
Knowledge added to semantic memory.
*****
*
***************
**
*****
***
**
**
*****
*
**
***
***
***
**
**
**
*
***
**
************
*
****
**
*
***
*
*
***
**
***
**
Total: 99 productions sourced.
% srand 1231231231

% w 0

% watch --level 0

% time d 10000
(0.334988s) real
```

That's a 2x not 20x difference.

**Comment by bluechill** [comment]
In addition internal stats are the same:

```
% stats
Soar 9.4.0 on Alexs-MacBook-Pro.local at Tue Jun  2 09:44:04 2015

99 productions (0 default, 99 user, 0 chunks)
   + 0 justifications
                                                        |   Computed
Phases:      Input   Propose   Decide   Apply    Output |     Totals
========================================================|===========
Kernel:      0.001    0.003    0.030    0.161    0.110  |      0.304
========================================================|===========
Input fn:    0.000                                      |      0.000
========================================================|===========
Outpt fn:                                        0.000  |      0.000
========================================================|===========
Callbcks:    0.000    0.000    0.000    0.000    0.000  |      0.000
========================================================|===========
Computed------------------------------------------------+-----------
Totals:      0.001    0.003    0.030    0.161    0.110  |      0.304

Values from single timers:
 Kernel CPU Time:       0.317 sec. 
 Total  CPU Time:       0.325 sec.

10000 decisions (0.032 msec/decision)
23546 elaboration cycles (2.355 ec's per dc, 0.013 msec/ec)
26753 inner elaboration cycles
7675 p-elaboration cycles (0.767 pe's per dc, 0.041 msec/pe)
38717 production firings (1.644 pf's per ec, 0.008 msec/pf)
276841 wme changes (138459 additions, 138382 removals)
WM size: 77 current, 78.494 mean, 180 maximum
% 
```

So, if I'm interpreting that correctly, the debugger takes 50% of the time which isn't bad considering it's sending across sockets.

**Comment by bluechill** [comment]
This occurs in the older arithmetic agent:

[Link](http://web.eecs.umich.edu/~soar/downloads/Agents/Arithmetic_Agent.zip)

**Comment by natederbinsky** [comment]
Update: if you take out all the (write) RHS calls, the time drops down [to the same as cli]. So apparently Mac/Linux is doing something dramatically worse when it comes to RHS/communication (this gets shown almost entirely in the Output phase of the `stats` command)?

**Comment by marinier** [comment]
It may just be that SWT is doing something dramatically worse when it comes
to writing text to the trace window. IIRC, SWT on linux/mac was not well
optimized for linux/mac when we first started using it (Soar 8.6), and it's
possible that's still the case. It could also be the particular text widget
type that the debugger is using and how it maps onto native widgets on each
platform -- the native linux/mac widgets that get used may be inherently
less efficient (e.g., because they have more features that we don't care
about).

It could also be how threading or redrawing is implemented on those
platforms (again, that's probably an SWT thing).

Bob

**Comment by natederbinsky** [comment]
It could be SWT. Note that this behavior occurs EVEN if you use "hide all" in the console filters. Thus, you won't *see* any output in the trace (i.e. probably not issues with text/scroll widgets), but you pay an enormous cost (note: I think that even with those filters, the debugger stores away the trace somewhere, so there are plenty of potential culprits).

**Comment by marinier** [comment]
Yes, the filters only impact the display, not the information. You can turn
the filters off and the information will all appear. (I'm not sure where
the data is stored if it's not being displayed -- does it really not touch
the display at all? If so, then it may not be SWT's fault). It could be JNI
on those platforms as well, since the data is still getting passed from C++
to Java, even if it's not being displayed.

The other thing to check is whether the display is synchronized
(right-click on trace window -> Properties -> Keep Soar Locked to Speed of
the Debugger). On windows it is not synchronized by default, but maybe it
is on the other platforms?

Bob

**Comment by natederbinsky** [comment]
Sigh. Bob, you are right. It's the Keep Soar Locked to Speed.

**Comment by garfieldnate** [comment]
What is the purpose of having a feature that makes Soar slower?

**Comment by marinier** [comment]
Soar runs way faster than the trace window can update. If they aren't
synchronized, you can end up in cases where you click the stop button (or
type the stop command), and the trace continues to fly by. In extreme cases
(e.g., high watch level and a long run), it can continue to fly by for
minutes. Soar is stopped, but the trace is still catching up. Synchronizing
the trace and Soar essentially makes Soar run at the trace's speed, which
means when you stop Soar, the trace stops immediately.
