### ISSUE TITLE
_snprintf vs _snprintf_s

### ISSUE THREAD

**Issue by bluechill** [SoarGroup/Soar#225]
@bazald @marinier @mazina 

On windows if you put Soar into a VS project you get errors related to _snprintf because it isn't considered safe.  The way to get around it is to either use _snprintf_s or define _CRT_SECURE_NO_WARNINGS.

Do we plan on fixing this or just, if you want to use a visual studio project, define _CRT_SECURE_NO_WARNINGS?

The difference is that _snprintf_s requires a buffer size.

**Comment by mazina** [comment]
No plans to update this
