### ISSUE TITLE
`print -f` can print rules with broken tests

### ISSUE THREAD

**Issue by bazald** [SoarGroup/Soar#227]
Reading in:

    sp {apply*move
       (state <s> ^operator <o>
                  ^count <c>
                  ^move <m>)
       (<o> ^name move
            ^direction <d>
            ^var <v>)
       (<s> ^<v> <old-value>)
       (<m> ^<d> {<new-value> <> <old-value>})
    -->
       (<s> ^count <c> -
            ^count (+ <c> 1) +)
       (<s> ^<v> <old-value> -
            ^<v> <new-value> +)
    }

You get out (with some cleanup):

    sp {apply*move
        (state <s> ^operator <o>
                   ^count <c>
                   ^move <m>
                   ^<v> { != <new-value> <old-value> })
        (<o> ^name move
             ^direction <d>
             ^var <v>)
        (<m> ^<d> <new-value>)
    -->
        (<s> ^count <c> -
             ^count (+ <c> 1) +
             ^<v> <old-value> -
             ^<v> <new-value> +)
    }

That test modification from `{<new-value> <> <old-value>}` to `{ != <new-value> <old-value> }` appears to be nonsense. It won't even read the rule back in, complaining that it "Expected variable or constant for test".

**Comment by mazina** [comment]
Rule couldn't be re-sourced because it was incorrectly printing "!=" instead of "<>".  Correct me if I'm wrong, but otherwise, it seems that the two rules are logically equivalent.  Printing issue fixed in latest commit.
