### ISSUE TITLE
o-support-mode command documentation incomplete

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#228]
The o-support-mode command documentation was modified at some point to remove the descriptions of modes lower than 3 -- presumably because those modes are no longer supported. However, the description for mode 3 builds on the description for mode 2, and thus without mode 2 being documented, it's not clear how mode 3 works (or mode 4, which builds on 3).

https://github.com/SoarGroup/Soar/wiki/cmd_o_support_mode

The simplest thing might be to put all the modes back (just copy from older documentation), and just make it clear which ones aren't supported. This also has the benefit of documenting history. An alternative solution would be to rewrite the description for 3 to include the relevant bits from the description of 2.

Another solution would be to stop kidding ourselves and remove support for mode 3 entirely (in the process, removing this command), and just ensure that the relevant part of the manual explains how O support mode works. After all, no one should be using mode 3, and my guess is no new features have been tested with it in years. For all we know, it's already broken. (Note that jsoar already does not support this command, and never has.)

**Comment by mazina** [comment]
Command no longer exists in Soar 9.6
