### ISSUE TITLE
svs_viewer (Soar 9.4.0) doesn't seem to render snowman example properly

### ISSUE THREAD

**Issue by bentito** [SoarGroup/Soar#233]
Yep nevermind the below, it was operator error, change all those "ball" and "position" to 'b' and 'p' and it works fine.
-------------------------------
Brand new to Soar, so maybe operator error here, but...

I start an svs_viewer instance under MacOS Yosemite from a terminal with the following command:
<code>./svs_viewer -s 65000</code>
Seems to start fine, I see a graph in a window.
I go to the Soar Debugger, start a kernel instance locally. So far so good. I issue the following commands:

<code>svs -e</code>
<code>svs connect_viewer 65000</code>
<code>connection successful</code>
<code>svs S1.scene.sgel add snowman world position 2 2 0</code>
<code>svs S1.scene.sgel add bottomball snowman ball 3 position 0 0 3</code>
<code>svs S1.scene.sgel add middleball snowman ball 2 position 0 0 8</code>
<code>svs S1.scene.sgel add topball snowman ball 1 position 0 0 11</code>

All I see in the svs_viewer window is the S! label up at the top-right and with each successive add command the label appears at the origin of the viewer, then each label gets written right on top of the next, they're all at the origin. Zooming in shows no ball shapes. Just a bunch of overwritten labels, all at the same point near the origin.

Here's a screenshot:
![svs_viewer_snowman_no_man](https://cloud.githubusercontent.com/assets/4449199/9822546/ff11b188-588e-11e5-9137-2f8224908ded.jpg)

Rotating the view does not change anything. They're just labels on top of each other with no geometry showing from all perspectives.

**Comment by amininger** [comment]
It should work correctly with either 'ball' or 'b' (similarly 'position' or 'p'). A bug was causing it to ignore any words longer than 1 character. This has been fixed on the master branch, so it will now work with both.
