### ISSUE TITLE
SendSVSInput not working but does work via ExecuteCommandLine

### ISSUE THREAD

**Issue by bentito** [SoarGroup/Soar#234]
I am trying to see if I am going about things the right way. I'd like to create some Java code that creates a scene graph. I have the following working and creating stuff:
<pre><code>
import sml.Kernel;
import sml.Agent;

public class SoarSVSJavaTest {
	public static void main(String[] args) {
		Kernel k = Kernel.CreateKernelInNewThread(64001);
		Agent a = k.CreateAgent("soar");
		System.out.println(a.ExecuteCommandLine("svs -e"));
		System.out.println(a.ExecuteCommandLine("svs connect_viewer 65000"));
		System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add snowman world p 2 2 0"));
		System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add bottomball snowman b 3 p 0 0 3"));
		System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add middleball snowman b 2 p 0 0 8"));
		System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add topball snowman b 1 p 0 0 11"));		
		System.out.println(a.ExecuteCommandLine("echo SnowMan Built"));
	}
}
</code></pre>

But then I see an example in the SVS docs that reads:
<pre><code>
(S1 ^svs S3)
  (S3 ^command C3 ^spatial-scene S4)
    (C3 ^add_node A1)
      (A1 ^id box5 ^parent world ^geometry box ^position P1 ^scale S6)
        (P1 ^x 1.0 ^y 1.0 ^z 0.0)
        (S6 ^x 0.1 ^y 0.1 ^z 0.1)
</code></pre>

I don't know how I'd send the code in this form using the above methodology? Entering commands in that form in the Soar debugger doesn't work either. 

Am I missing a better way (more API-ey way?) of sending all this? Have skimmed the tutorials, trying to glean what I need for just using SGEL and SVS for this and have been trying to avoid getting more involved in Soar at this point. Sorry if I've missed something obvious and crucial.

Thanks,
Brett

**Comment by amininger** [comment]
There are multiple ways of interacting with SVS and modifying the scene
graph:

1. Through soar commands (what you would type in the soar command line
interface or debugger). This is what you are currently using with
'agent.ExecuteCommandLine'

2. Through the sml interface by sending SGEL commands via
agent.SendSVSInput(string sgel). This is what I would recommend you use if
trying to do things from a java program. You can either call it multiple
times with each command, or concatenate all the commands together separated
by newlines.

Example:

a.SendSVSInput("add snowman world p 2 2 0");

a.SendSVSInput("add bottomball snowman b 3 p 0 0 3");

or to do it all at once:

String commands = "add snowman world p 2 2 0\n";
commands += "add bottomball snowman b 3 p 0 0 3\n";
...
a.SendSVSInput(commands)

3. From within a soar agent through soar rules putting commands on the
svs.command link. So the example you listed with add_node is for the soar
agent to modify the scene graph itself. An example rule would look
something like this:

sp {top-state*create*ball
(state <s> ^superstate nil
           ^svs.command <cmd>)
-->
(<cmd> ^add_node <add>)
(<add> ^id ball1 ^parent world ^geometry ball ^position <p1>)
(<p1> ^x 0 ^y 5 ^z 1)
}



So the method you want depends on your use case. If you want to add
information from an external environment into soar so the agent can have
access to a spatial representation of the world, you should use sml
commands (#2). If your soar agent itself is creating or modifying the
world, say to create some imagined world configuration, then do it through
soar rules by creating svs commands (#3).

So based on your question, I would recommend changing to
agent.SendSVSInput.

If you have any other questions just let me know
-Aaron Mininger

**Comment by bentito** [comment]
Hi Aaron,
Thanks very much for the prompt reply:

So I changed my Java to look like this:

import sml.Kernel;
> import sml.Agent;
>


> public class SoarSVSJavaTest {
> public static void main(String[] args) {
>
Kernel k = Kernel.CreateKernelInNewThread(64001);

Agent a = k.CreateAgent("soar");

a.SendSVSInput("add snowman world p 2 2 0");
>
System.out.println(a.GetSVSOutput());

// System.out.println(a.ExecuteCommandLine("svs -e"));

// System.out.println(a.ExecuteCommandLine("svs connect_viewer 65000"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add snowman
> world p 2 2 0"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add bottomball
> snowman b 3 p 0 0 3"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add middleball
> snowman b 2 p 0 0 8"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add topball
> snowman b 1 p 0 0 11"));

System.out.println(a.ExecuteCommandLine("echo SnowMan Built"));

}

But the output of GetSVSOuput() reads:

> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGSEGV (0xb) at pc=0x00007fff8ce5b152, pid=11976, tid=4867
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0-b132) (build
> 1.8.0-b132)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.0-b70 mixed mode
> bsd-amd64 compressed oops)
> # Problematic frame:
> # C  [libsystem_c.dylib+0x1152]  strlen+0x12


 And nothing shows up in the svs_viewer.

That output isn't helping me debug...?

Thanks,
brett



Brett Tofel
(802) 765-0440

**Comment by amininger** [comment]
Sorry for not responding sooner.

You should still have these two lines included to enable svs and connect it
to the viewer.

System.out.println(a.ExecuteCommandLine("svs -e"));
System.out.println(a.ExecuteCommandLine("svs connect_viewer 65000"));

By the way, right now the GetSVSOutput command isn't implemented, so
there's not a good way to get information about the current scene graph
from java. Also, make sure your java program doesn't exit, otherwise the
agent would be deleted and northing would show up in the viewer.

Hi Aaron,
Thanks very much for the prompt reply:

So I changed my Java to look like this:

import sml.Kernel;
> import sml.Agent;
>


> public class SoarSVSJavaTest {
> public static void main(String[] args) {
>
Kernel k = Kernel.CreateKernelInNewThread(64001);

Agent a = k.CreateAgent("soar");

a.SendSVSInput("add snowman world p 2 2 0");
>
System.out.println(a.GetSVSOutput());

// System.out.println(a.ExecuteCommandLine("svs -e"));

// System.out.println(a.ExecuteCommandLine("svs connect_viewer 65000"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add snowman
> world p 2 2 0"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add bottomball
> snowman b 3 p 0 0 3"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add middleball
> snowman b 2 p 0 0 8"));

// System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add topball
> snowman b 1 p 0 0 11"));

System.out.println(a.ExecuteCommandLine("echo SnowMan Built"));

}

But the output of GetSVSOuput() reads:

> # A fatal error has been detected by the Java Runtime Environment:
> #
> # SIGSEGV (0xb) at pc=0x00007fff8ce5b152, pid=11976, tid=4867
> #
> # JRE version: Java(TM) SE Runtime Environment (8.0-b132) (build
> 1.8.0-b132)
> # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.0-b70 mixed mode
> bsd-amd64 compressed oops)
> # Problematic frame:
> # C [libsystem_c.dylib+0x1152] strlen+0x12


And nothing shows up in the svs_viewer.

That output isn't helping me debug...?

Thanks,
brett



Brett Tofel
(802) 765-0440

On Tue, Sep 15, 2015 at 1:25 PM, Aaron Mininger <notifications@github.com>
wrote:

> There are multiple ways of interacting with SVS and modifying the scene
> graph:
>
> 1. Through soar commands (what you would type in the soar command line
> interface or debugger). This is what you are currently using with
> 'agent.ExecuteCommandLine'
>
> 2. Through the sml interface by sending SGEL commands via
> agent.SendSVSInput(string sgel). This is what I would recommend you use if
> trying to do things from a java program. You can either call it multiple
> times with each command, or concatenate all the commands together
separated
> by newlines.
>
> Example:
>
> a.SendSVSInput("add snowman world p 2 2 0");
>
> a.SendSVSInput("add bottomball snowman b 3 p 0 0 3");
>
> or to do it all at once:
>
> String commands = "add snowman world p 2 2 0\n";
> commands += "add bottomball snowman b 3 p 0 0 3\n";
> ...
> a.SendSVSInput(commands)
>
> 3. From within a soar agent through soar rules putting commands on the
> svs.command link. So the example you listed with add_node is for the soar
> agent to modify the scene graph itself. An example rule would look
> something like this:
>
> sp {top-state*create*ball
> (state <s> ^superstate nil
> ^svs.command <cmd>)
> -->
> (<cmd> ^add_node <add>)
> (<add> ^id ball1 ^parent world ^geometry ball ^position <p1>)
> (<p1> ^x 0 ^y 5 ^z 1)
> }
>
>
>
> So the method you want depends on your use case. If you want to add
> information from an external environment into soar so the agent can have
> access to a spatial representation of the world, you should use sml
> commands (#2). If your soar agent itself is creating or modifying the
> world, say to create some imagined world configuration, then do it through
> soar rules by creating svs commands (#3).
>
> So based on your question, I would recommend changing to
> agent.SendSVSInput.
>
> If you have any other questions just let me know
> -Aaron Mininger
>
> On Tue, Sep 15, 2015 at 12:31 PM, Brett Tofel <notifications@github.com>
> wrote:
>
> > I am trying to see if I am going about things the right way. I'd like to
> > create some Java code that creates a scene graph. I have the following
> > working and creating stuff:
> >
> >
> > import sml.Kernel;
> > import sml.Agent;
> >
> > public class SoarSVSJavaTest {
> > public static void main(String[] args) {
> > Kernel k = Kernel.CreateKernelInNewThread(64001);
> > Agent a = k.CreateAgent("soar");
> > System.out.println(a.ExecuteCommandLine("svs -e"));
> > System.out.println(a.ExecuteCommandLine("svs connect_viewer 65000"));
> > System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add snowman
> world p 2 2 0"));
> > System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add
> bottomball snowman b 3 p 0 0 3"));
> > System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add
> middleball snowman b 2 p 0 0 8"));
> > System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add topball
> snowman b 1 p 0 0 11"));
> > System.out.println(a.ExecuteCommandLine("echo SnowMan Built"));
> > }
> > }
> >
> > But then I see an example in the SVS docs that reads:
> >
> >
> > (S1 ^svs S3)
> > (S3 ^command C3 ^spatial-scene S4)
> > (C3 ^add_node A1)
> > (A1 ^id box5 ^parent world ^geometry box ^position P1 ^scale S6)
> > (P1 ^x 1.0 ^y 1.0 ^z 0.0)
> > (S6 ^x 0.1 ^y 0.1 ^z 0.1)
> >
> > I don't know how I'd send the code in this form using the above
> > methodology? Entering commands in that form in the Soar debugger doesn't
> > work either.
> >
> > Am I missing a better way (more API-ey way?) of sending all this? Have
> > skimmed the tutorials, trying to glean what I need for just using SGEL
> and
> > SVS for this and have been trying to avoid getting more involved in Soar
> at
> > this point. Sorry if I've missed something obvious and crucial.
> >
> > Thanks,
> > Brett
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/SoarGroup/Soar/issues/234>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoarGroup/Soar/issues/234#issuecomment-140472963>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/SoarGroup/Soar/issues/234#issuecomment-140490625>.

**Comment by bentito** [comment]
Sorry for delay in testing this, but I cannot seem to make this work with SendSVSInput. The commented out line with the ExecuteCommandLine works fine and instantly shows the item in the viewer. The previous line fails.

<pre><code>
import sml.Kernel;
import sml.Agent;

public class SoarSVSJavaTest {
	public static void main(String[] args) {
		Kernel k = Kernel.CreateKernelInNewThread(64001);
		Agent a = k.CreateAgent("soar");
		System.out.println(a.ExecuteCommandLine("svs -e"));
		System.out.println(a.ExecuteCommandLine("svs connect_viewer 65000"));
		a.SendSVSInput("add snowman world p 2 2 0");
//		System.out.println(a.ExecuteCommandLine("svs S1.scene.sgel add snowman world p 2 2 0"));
		while (true) {
			//need to not exit so viewer can show stuff
		}
}
</code></pre>

**Comment by mazina** [comment]
In the future, I would use the soar-help mailing list for questions: https://lists.sourceforge.net/lists/listinfo/soar-help.  If you're still having problems, feel free to paste this thread into a new mailing list question.  As it has been a couple weeks, I'm closing this issue.

**Comment by bentito** [comment]
Okay, but there is still an unaddressed failure of what I believe should be working code.

**Comment by mazina** [comment]
OK.  It's been a while, so I didn't know if you took the question off line or solved it on your own.  If you guys think it's a bug, I'll re-open and change the title.

**Comment by bentito** [comment]
Yes. Bug I think

**Comment by amininger** [comment]
What is happening is that when the commands are sent via SendSVSInput, they are not processed until the end of the input phase. So you need to step the agent one decision cycle. Try adding the following command after the SendSVSInput:
a.RunSelf(1);

This command will run the agent 1 decision cycle. This should cause the word 'snowman' to appear in the viewer. (Since no geometry is given, it creates an empty node. If you want to see a ball with radius 4 in the viewer, try extending the command to be SendSVSInput("add snowman world p 2 2 0 b 4"); )

**Comment by bentito** [comment]
Okay, thanks for the explanation of the need to call RunSelf. My code works
now.

Brett Tofel
(802) 765-0440
