### ISSUE TITLE
Bogus warning message

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#235]
In the Soar Manual, figure 3.1 (page 37/45) depicts an identifier being used as an attribute. This seems to imply that this sort of rule should work (the strange variable names match up with the figure):

    sp "test
       (state <o43> ^<x44> 200)
       (<x44> ^unit grams ^property mass)
    -->
       (write (crlf) Success)
    "
However, when I try to load this rule (in csoar 9.4.0), I get the message:

    Warning: On the LHS of production test, identifier <x44> is not connected to any goal or impasse.

The rule loads just fine, though. John tested on 9.3.3 and 9.5 for me and confirmed the warning appears there, too. FWIW, it also appears in JSoar.

**Comment by mazina** [comment]
The code that prints that warning, in collect_root_variables(), definitely
does not compare against the attribute element and hasn't as far back as
9.3.2.  It doesn't seem like an oversight or bug from the way the code is
(more than one piece of the logic skips the attribute element), and I'm
fairly sure multiple places in the code that assume that attributes can't
contain identifiers and treats them differently.  And I don't think any of
the code that walk through wme's ever look at the attribute element to see
if it's a link to another wme.

So, I'd argue that we should change the example in the manual and have both
the parser/chunker disallow rules like that.  If we want to allow
attributes to provide links between identifiers, I think we'd need to do a
good bit of work to make sure that Soar could handle that.  My guess is
that a lot of buggy behavior could occur if an agent tried to do that
liberally.

Do you actually want to do this Bob, or is this just an observation about
the manual?

**Comment by marinier** [comment]
Whether to keep this feature or not is a call for John to make. I know that
smem and epmem don't support ids as attributes -- Nate didn't realize that
was a thing until it was too late :) But for normal rules, it definitely
works. This came up because I'm working on some legacy code that uses ids
as attributes to create complex output commands.

I think this is a neat feature and I would have used it several times if
epmem and smem supported it. But because they don't I never do. If there
are no plans to ever fix this, then it seems unlikely this feature will be
useful going forward.

**Comment by mazina** [comment]
I spoke to John and he said he understood it was no longer fully supported,
though it once was. Adding support for it would be a challenge, even if we
ignore smem/epmem.  For what it's worth, my guess is that legacy code that
uses identifiers in the attribute slot could have big problems in the
current code base.  A recent bug we were tracking down that involved the
link count between identifiers caused both a memory leak and disappearing
wme's.  I could see similar link count issues as a result of these type of
rules.  Also, I think the current chunking code would also have problems.

For now, I can at least change the message to be less bogus, something like:

Warning: On the LHS of production test, <x44> is the identifier of a
condition but is not grounded to any goal or impasse. Rule needs a
condition of the form (<goal> ^attribute <x44>). Note that using
identifiers in an attribute slot is not supported in the current version of
Soar.

**Comment by marinier** [comment]
Updating the warning seems like a reasonable solution. Maybe even say the
feature is deprecated, so people know not to rely on it because it'll
probably go away entirely at some point.

**Comment by mazina** [comment]
OK, I'll get that changed for the next release.

**Comment by mazina** [comment]
Example of the new warning:

Warning for production "no-root-rule":
   On the LHS of production, the symbol <bar> is the identifier element of a
   condition but is not linked to any goal or impasse, either directly in a
   condition or indirectly through other conditions.

   Note: Soar does not condition the attribute element of a condition when
   determining whether there is a link between two identifiers.  Using Soar
   identifiers in an attribute slot may work but is not fully supported in the
   current version of Soar.

**Comment by marinier** [comment]
I'm not sure what the sentence "Soar does not condition the attribute
element of a condition when determining whether there is a link between two
identifiers." means. Does that have something to do with chunking? I think
it might be better to just drop that sentence and leave the next sentence.
If you want, you could say something more specific like, "Using Soar
identifiers in an attribute slot may work for rule matching but is not
supported in episodic memory, semantic memory, or chunking. Identifier
attributes should be considered deprecated."

**Comment by mazina** [comment]
Sorry, that was a typo.  It was supposed to be "Soar does not consider".  I'll change the second sentence to your more specific version.

**Comment by marinier** [comment]
Ok, that helps, but I still don't understand what it means. Does that mean
that variables in rules won't get bound correctly? Because I'm pretty sure
that works. For example, this works in Soar 9.5:

sp "test
(state <s> ^superstate nil)
-->
(<s> ^<x> <y>)
(<x> ^isa attribute)
(<y> ^isa value)
"

sp "test2
(state <s> ^<x> <y>)
(<x> ^isa attribute)
(<y> ^isa value)
-->
(write (crlf) works)
"

**Comment by mazina** [comment]
I didn't mean to imply that things have changed.   As far as I know, using identifiers in the attribute element should work as well as it did before.  

But, I see why it's confusing now.  How about "Soar does not consider the attribute element of a condition when determining whether two conditions are connected"?

**Comment by marinier** [comment]
I still don't know what that means. To me, Soar is treating conditions as
connected from a variable binding perspective. What do you mean by
conditions being connected?

**Comment by mazina** [comment]
I was trying to use connected in the same, or at least similar, sense of the original warning:  "Warning: On the LHS of production no-root-rule, identifier <bar> is not connected to any goal or impasse." So, I'd say two conditions would be connected if the value symbol of one is the same as the identifier symbol in another or if one condition is connected to a third condition that is connected to the other condition.

It seemed like saying conditions are connected would be more intuitive than saying the identifiers are connected, but perhaps not?

**Comment by marinier** [comment]
But the original warning is wrong -- the conditions are connected (as per
my example). The code that generates the warning just fails to check for
this -- the rete matching checks for it just fine. FWIW, the original
warning is very confusing, too.

**Comment by mazina** [comment]
I understand what you're saying about it being wrong.  I do think we've previously considered them connected just like the example in the manual you pointed out out, and that the rete matches them fine, so systems may still be able to use them without a problem.  I'm not even certain that the potential issues I'm worried about are really problems, like chunking and link tracking/garbage collection.  Ideally, this would be a great feature to support again.  That said, it seems like we shouldn't consider conditions like that connected if that connection is based on a feature that's now deprecated.  

In any case, I was just trying to make the connection between why the rule in question might be problematic and the fact we don't support identifiers in attributes.  Most people will get the warning when they make simple mistakes in their rules, so it seemed to me that just pointing out they can't have STIs in attributes would seem random to most users.

Anyway, it seems like we've put an undue amount of analysis to a warning, so I'll run it past John and get his take on it.   Thanks for all the feedback, Bob!

**Comment by mazina** [comment]
btw, here's what I'm going to propose this time based on our discussion.  I took out the connected conditions/identifiers part.

Warning for production "no-root-rule":
   On the LHS of production, the symbol <bar> is not linked to any goal or impasse, 
   either directly in a condition or indirectly through other conditions.

   Note: Soar does not consider the attribute element of a condition when
   determining whether a symbol is connected to a goal or impasse.  Using Soar
   identifiers as attributes may work but is not fully supported in the
   current version of Soar.

**Comment by marinier** [comment]
That looks good to me! I think it's much clearer now.

-----Original Message-----

**Comment by mazina** [comment]
Excellent.  Looks ok to John too, so it's committed.
