### ISSUE TITLE
Parser treats numeric attributes as floats

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#236]
@garfieldnate changed the parser as discussed in issue #136 to allow dot notation to work before numeric attributes; e.g., `(<s> ^number.1 yes)` produces something like `(<s> ^number <n*1>) (<n*1> ^1 yes)`. This is great.

However, switching this around is still problematic. E.g., `(<s> ^1.number yes)` produces `(<s> ^1. number ^1. yes)`.

What would be preferable in this case is to get something like `(<s> ^1 <1*1>) (<1*1> ^number yes)`.

There is a tricky bit here -- what if we actually want a floating point number as an attribute? In this case, I think the reasonable behavior is to say if the string after the dot can be resolved as a number, then treat it as a floating point value. Otherwise treat it as an integer.

Examples:
`(<s> ^1.number yes)` produces `(<s> ^1 <1*1>) (<1*1> ^number yes)`
`(<s> ^1.1 yes)` produces `(<s> ^1.1 yes)`
`(<s> ^1.1a yes)` produces `(<s> ^1 <1*1>) (<1*1> ^1a yes)`

If you want a floating point attribute, then you can't use dot notation. But I think using integers as attributes is far more common, and thus this is far better than the current behavior. Even if we just supported the first two examples above (I don't know if the last example is harder), that would be an improvement.

**Comment by garfieldnate** [comment]
I'll see if I can take a look next week (silver week here). Luckily this doesn't involve the parser, just the tokenizer, which is much simpler code. There's already a function in there for checking if a string can be resolved as a number (`1.1a` will be a string but `1.1e` will be a float, I think).

**Comment by garfieldnate** [comment]
Current behavior for your three test cases:

    % sp {test1
    (state <s> ^1.number yes)
    -->
    }
    *
    % sp {test2
    (state <s> ^1.1 yes)
    -->
    }
    *
    % sp {test3
    (state <s> ^1.1a yes)
    -->
    }
    *
    % p test1
    sp {test1
        (state <s> ^1. number ^1. yes)
        -->

    }
    % p test2
    sp {test2
        (state <s> ^1.1 yes)
        -->

    }
    % p test3
    sp {test3
        (state <s> ^1.1 a ^1.1 yes)
        -->

    }
    %

**Comment by garfieldnate** [comment]
The cause has to do with how the lexer reads floating point numbers. It looks at previous characters and decides the lexeme could be a floating point, then it calls `read_rest_of_floating_point_number`, which reads the rest of the number, stopping when an unrelated character is found (something that isn't a digit, +, -, e, or E). That doesn't check for spacing or anything afterwards to indicate that it actually read a complete token; it simply sends back the number, and following characters are placed in the next lexeme. You can see the problem with the above tests, which call `read_rest_of_floating_point_number` from `lex_digit`, or with this test:

    sp {test4
        (state <s> ^.1a yes) # becomes ^0.1 a ^0.1 yes
    -->
    }

which calls it from `lex_period`.

I think the most straightforward fix would be to edit `read_rest_of_floating_point_number` to restore lexer state and return false when it realizes it hasn't actually been handed a floating point number. 

I need a little guidance for the check itself, though. Will a simple check for a letter suffice? The other constituent characters are `$%&*+-/:<=>?_@`, and they can either be made to start a new lexeme, or they can be considered part of a string starting with a number. Soar allows lots of crazy strings. Should we make `^.1456$%` a string identifier `^|.1456$%|` or a floating point identifier `^.1456` and then let `$%` be the string value (or whatever it turns out to be, an error possibly)?

**Comment by marinier** [comment]
I think that lexmes like this should generally be separated by whitespace.
Otherwise it's too confusing. Thus, ^.1456$% should be the string ^|.1456$%|.
This would also seem to imply that ^a^b should be parsed as ^|a^b| and not
^a <a*1> ^b <b*1> (which is what it does now). But maybe that's a whole
other issue that should be handled separately from the numbers.

**Comment by garfieldnate** [comment]
The lexer deals with three classes of characters: numbers, constituents, and non-constituents. Similarly to `read_rest_of_floating_point_number`, several methods call `read_constituent_string`, which reads alphanumeric and `$%&*+-/:<=>?_@`; they then call `determine_type_of_constituent_string` to see what they got back. All of the valid non-constituent characters (caret, parens, braces, etc.) have their own lexer methods, and they simply read the one character and move on to the next lexeme. Your example change for `^a^b` would, I think, be the beginning of a slippery slope in lexer changes, and I think it makes sense to leave the handling of these non-constituent characters as-is.

Changing float/dot handling is a comparatively isolated change for fixing a possible "gotcha" ambiguity in the grammar, and I think it will be worth the change.

Along those lines, I think whatever lexeme is read in with the number should at least stop at the next constituent character; so ^.1234a^b would be ^|.1234a| ^b. That would probably make the behavior most consistent and explainable.

**Comment by marinier** [comment]
That sounds very reasonable to me.

**Comment by garfieldnate** [comment]
There's also this bit of current behavior:

    sp {test6
    (state <s> ^.tf& yes)
    -->
    }
    Error: Expected variable or constant for test
    (Ignoring production test6)

which I think means that you can't start a WME name with a period unless you quote it. I'll try to change current behavior as little as possible; The manual probably says you can't start names with dots.

**Comment by garfieldnate** [comment]
I believe the work for this is done (https://github.com/garfieldnate/Soar/commit/d91854e58839ef591a781593a6e94490b44f6c70), but I currently can't compile or run the tests, so I'll send a PR after that becomes possible again.

**Comment by garfieldnate** [comment]
The new behavior looks like this:

    % sp {test1
    (state <s> ^1.number yes)
    -->
    }
    *
    % sp {test2
    (state <s> ^1.1 yes)
    -->
    }
    *
    % sp {test3
    (state <s> ^1.1a yes)
    -->
    }
    *
    % sp {test4
        (state <s> ^.1a yes) # becomes ^0.1 a ^0.1 yes
    -->
    }
    Error: Expected variable or constant for test
    (Ignoring production test4)

    Production addition failed.
    % p test1
    sp {test1
        (state <s> ^1 <v*1>)
        (<v*1> ^number yes)
        -->

    }
    % p test2
    sp {test2
        (state <s> ^1.1 yes)
        -->

    }
    % p test3
    sp {test3
        (state <s> ^1 <v*1>)
        (<v*1> ^1a yes)
        -->

    }

The error loading test4 is because you `^.` is not sensible, and we don't interpret `.1a` as a float.

@marinier What do you think?

**Comment by marinier** [comment]
I think this looks good. Agree that test4 should be an error, assuming that
^|.1a| works as an attribute. The key aspects of the design are to still
make it possible to have any number or string as an attribute, but to make
the most common cases behave as expected by default (i.e., assume dots mean
dot notation if not interpretable as a float). This looks to have achieved
these goals.

**Comment by garfieldnate** [comment]
Good. Your example works, too:

    % sp {test5
    (state <s> ^|.1a|)
    -->
    }
    *
    % p test5
    sp {test5
        (state <s> ^|.1a| <v*1>)
        -->

    }

We can merge it once tests have run successfully (unrelated issue).
