### ISSUE TITLE
"cli" is too vague a name

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#237]
Normally users can add directories containing executables to their path so that they can access them anywhere. The Soar CLI, however, presents a problem because it has such a vague name. When I add my soar/bin directory to my path and try to run "cli.exe" from somewhere, my CMD ends up using a random "CLI.exe" from some driver that came with my computer. I think "cli" might be too vague/common a name, and it would be better to name it something more descriptive like "soar_cli" or something (also "soar_mcli"). 

Would this change break many things? I would like it because I am trying to access the CLI in an IDE, and it needs to be on the path (and an exact path won't work when I share the IDE package with other users).

**Comment by mazina** [comment]
I've never had a conflict, but I can see how that could be a common name.  

I don't think it would break anything.  Most people seem to use the java debugger for everything.  Perhaps a clearer name would be to simply call the executable soar and msoar/multisoar.

**Comment by garfieldnate** [comment]
Yes, I think the Java debugger is used much more commonly. :+1: for soar and msoar. Easy to remember and consistent with other languages: ruby, perl, python, java, etc.

**Comment by marinier** [comment]
I don't think SoarTech has an opinion about this (we haven't experienced
problems), so if you want to change it, feel free. I wonder if this implies
that JavaSoarDebugger should be renamed to something more consistent with
this; e.g., soar-gui or soar-debugger (having Java in the name isn't really
necessary). Not that I want to turn a simple renaming of some rarely used
tools into a bigger deal than it has to be.
