### ISSUE TITLE
SVS documentation fixes

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#240]
The SVS chapter in the manual has a few minor typos:
- The first example (figure 8.1) and the text on page 124 (last sentence before section 8.4.1) say that a result of false is represented by the value "f". But the example right before that sentence and other examples (e.g., at the end of 8.3.7) show "false" instead.
- The last sentence in section 8.1.1 is not quite grammatical. I think maybe the comma should be a semi-colon.
- In section 8.5.1, the sentence crossing the page boundary of 127-128 should not have the word "if".
- The second sentence in section 8.5.1.1, "combination" is misspelled.

Also, a couple clarifications would be helpful:
- Section 8.5 does not actually say that the kernel needs to be recompiled. This should be made explicit.
- As per the recent email on soar-help, it should be made clear when SVS updates, and thus to see some changes the agent needs to run a little. (It would be worth showing a version of the decision cycle that shows when all the Soar 9 stuff happens -- when the various links are read and when results are created for svs, epmem, smem, and rl.)

**Comment by mazina** [comment]
Put on the list for the upcoming release.

**Comment by mazina** [comment]
Aaron has updated SVS chapter in manual
