### ISSUE TITLE
Edge case when printing attribute with empty name

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#242]
On the subject of `^.att` being illegal, I thought maybe a user might want an attribute with an empty name. No, noone sane would want that, but maybe someone's code generator could accidentally make code like that. Anyway, if you source a production with an empty attribute name and print it out again, the printed production will be unsourceable:

    % sp {test6
    (state <s> ^||)
    -->
    }
    *
    % p test6
    sp {test6
        (state <s> ^ <v*1>)
        -->

    }
    % sp {test7
    (state <s> ^)
    -->
    }
    Error: Expected variable or constant for test
    (Ignoring production test7)

The printed production should use `|` quotes here.

**Comment by marinier** [comment]
Sounds like the readreable flag should be set for empty string. This is
what causes strings to print with pipes. I forget the exact logic, but it's
something like any string that starts with a capital letter (so strings
that sort of look like identifiers get put in pipes to make it clear) and
strings that look like numbers. Adding a check for empty string should be
straightforward (although I'm not sure if similar logic exists in multiple
places for printing things -- e.g., working memory, epmem, and smem
printing maybe should also be updated).
