### ISSUE TITLE
Document and support SoarJavaDebugger arguments

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#247]
SoarJavaDebugger supports a number of command line arguments; see starting at line 119 here:

https://github.com/SoarGroup/Soar/blob/development/Java/Debugger/src/edu/umich/soar/debugger/SWTApplication.java

However, these do not appear to be documented outside of the code. Worse, the SoarJavaDebugger.bat file (and similar on other platforms, I imagine), does not pass command line args through to java.

A simple modification to the .bat may be sufficient; e.g., change the java line to something like:

    start javaw -jar bin\SoarJavaDebugger.jar %1 %2 %3

...adding as many % as needed to support all possible arguments.

FYI, one reason this is useful is for setting up an Eclipse external program launch to run the debugger, using the -source arg to load the agent code.

**Comment by mazina** [comment]
Implemented in a commit the last couple weeks.
