### ISSUE TITLE
Call to agent.DestroyWME blocks forever

### ISSUE THREAD

**Issue by bauerj** [SoarGroup/Soar#252]
I'm using the Python SML interface to control SOAR execution.

The following code produces weird results:

```python
input_link = agent.GetInputLink()
print "Deleting old input link"
for element in ['a', 'b', 'c']:
                try:
                    print "Destroying ", element
                    toBeDestroyed = input_link.FindByAttribute(element, 0)
                    print toBeDestroyed
                    self.agent.DestroyWME(toBeDestroyed)
                    print "Destroyed!"
                except:
                    print "Exception occured"
```
The following output occurs:

    Deleting old input link
    Destroying  a
    <Python_sml_ClientInterface.WMElement; proxy of <Swig Object of type 'sml::WMElement *' at 0x0000000004966C90> >

I would have expected either a "Destroyed!" or an "Exception occured" message, but, as you can see, there is neither.

Apparently the call to `DestroyWME` never returns. Is there anything wrong with this code? I couldn't find any real documentation on the interface so maybe that's not how I'm supposed to clear the input link.

Any advice on what to use instead or how to debug this futher would be appreciated.

**Comment by amininger** [comment]
It could be a synchronization issue. It is really only safe to modify working memory at very specific times when the agent is paused, and usually either during the input phase or output phase. The best practice is to add an run event listener, probably before the input phase if you are modifying the input link. Here is an example in java, I apologize but I have not used sml in python, it should be straight forward to convert. The handler itself implements the RunEventInterface and should implement the function:

```
void runEventHandler(int event, Object data, Agent agent, int phase)
   event - the run event id, can convert into smlRunEventId enum
   data - a pointer to the object you passed in to the RegisterForRunEvent function (can be null)
   agent - the agent this event happened with
   phase - the phase the agent is in, can convert into smlPhase
```

Here is the full example:

```
agent.RegisterForRunEvent(smlRunEventId.smlEVENT_BEFORE_INPUT_PHASE, 
   new RunEventInterface(){
      public void runEventHandler(int event, Object data, Agent agent, int phase) {	
         // in this example, this will be smlRunEventId.smlEVENT_BEFORE_INPUT_PHASE
         smlRunEventId eventId = smlRunEventId.swigToEnum(event);
         
         // in this example, this will be smlPhase.sml_INPUT_PHASE
         smlPhase phaseId = smlPhase.swigToEnum(phase);
        			
         // modify agent/working memory here
        			
         agent.Commit();
      }
   }, null);
```

**Comment by bauerj** [comment]
You are totally right. I tried to delete the WME items while the agent was still running. In hindsight, it's clear that that's not a smart idea.

Registering for the event and updating it there works flawlessly.

Thanks for your help! :smiley:
