### ISSUE TITLE
Set debugging port with SML interface

### ISSUE THREAD

**Issue by bauerj** [SoarGroup/Soar#253]
Is there any way to set the port on which the kernel listens for connections from the debugger (e.g. remote connections)?

I'm able to get the port with `sml::Kernel::GetListenerPort()` but there seems to be no `SetListenerPort` method.

**Comment by mazina** [comment]
When you create the kernel, the port is a parameter you can pass in.

**Comment by bauerj** [comment]
Thanks, that worked!

Is there a documentation of all the methods and parameters somewhere?

**Comment by mazina** [comment]
Only the documents on the web site:
http://soar.eecs.umich.edu/articles/articles/soar-markup-language-sml.

The SML code is pretty well commented, though, so one thing you could do is
use doxygen to generate some documentation to get familiar with the API.  I
believe the comments are in a format that allows doxygen to pull the
function descriptions into the web pages it generates.

Here's one that a previous student posted several years ago, which I'm a
bit surprised is still available.  It might be a bit out of date, but then
again, I don't think the SML API has changed in those years.
http://winter.eecs.umich.edu/~jzxu/sml/
