### ISSUE TITLE
Deleting the last remaining agent when using soar cli causes a segfault.

### ISSUE THREAD

**Issue by scijones** [SoarGroup/Soar#264]
I will compile soar from development, navigate to out and run "./soar". I use "list" to see the available agent. Sometimes I'll add additional agents before, but it doesn't seem to matter. I'll delete the agent(s) one by one. The delete of the last remaining agent causes a segfault.

I never actually need to do this, mind you. It's just a thing.

**Comment by mazina** [comment]
Fixed in latest commit.  (It just won't let you delete it.)
