### ISSUE TITLE
SoarJavaDebugger seg faulting on macOS Sierra

### ISSUE THREAD

**Issue by petosegan** [SoarGroup/Soar#269]
SoarJavaDebugger is crashing on launch with jdk-8u112 and macOS Sierra 10.12.1

Log file is attached. The debuggers in SoarSuite 9.4.0 and SoarTutorial 9.4.0 also crash with similar errors.

[hs_err_pid6418.txt](https://github.com/SoarGroup/Soar/files/681557/hs_err_pid6418.txt)

**Comment by mazina** [comment]
Try switching the launch script to this:
```
#!/bin/bash
export SOAR_HOME="$(dirname "$0")"
export DYLD_LIBRARY_PATH="$SOAR_HOME"
cd $(dirname "$0")
java -XstartOnFirstThread -Djava.library.path="$SOAR_HOME" -jar "$SOAR_HOME/SoarJavaDebugger.jar" &
```

**Comment by petosegan** [comment]
That fixed it, thank you!
