### ISSUE TITLE
New version of deep copy needs refcount audit

### ISSUE THREAD

**Issue by mazina** [SoarGroup/Soar#270]
This issue is to document an identifier symbol refcount leak that can occur with Soar 9.6 has a new version of deep copy.  Deep copy was changed so that chunking can properly learn from it and is more robust in general.  (FYI, the old version of deep copy also had this issue along with many others.)

Here is an agent that demonstrates the leak.  Run agent and init-soar.  In the debug build, it will show that symbol F1 still has a refcount of 1.  Note that the agent in question does not learn any chunks or justifications, so this does not seem to involve EBC.

[deep_copy_refcount_leak.soar.zip](https://github.com/SoarGroup/Soar/files/704950/deep_copy_refcount_leak.soar.zip)

**Comment by mazina** [comment]
Resolved in latest commit.

**Comment by marinier** [comment]
Will this fix be in the nightly builds, or is it on a separate branch?

**Comment by mazina** [comment]
The current development and master branches include this change.
