### ISSUE TITLE
High CPU usage when creating kernel in new thread

### ISSUE THREAD

**Issue by adeschamps** [SoarGroup/Soar#273]
The following program causes one core to run at 100%. I would have expected it to spend most of its time sleeping.

I've tested this on Ubuntu 14.04 with a nightly build, as well as Arch where I compiled from the development branch.

```C++
#include <chrono>
#include <sml_Client.h>
#include <thread>

int main()
{
    auto* kernel = sml::Kernel::CreateKernelInNewThread();
    auto* agent = kernel->CreateAgent("test-agent");
    while (true) {
        std::cerr << "Tick\n";
        agent->RunSelf(1);
        std::this_thread::sleep_for(std::chrono::seconds(1));
    }
}
```

Is this the wrong way to run an agent slowly?

**Comment by bluechill** [comment]
I believe this is because it's just a busy loop on the back end if you tell Soar to create the thread. If you want to run an agent slowly or manually handle agent steps then I'd create the thread yourself and manually call step when you want to advance the agent.

Alex

**Comment by adeschamps** [comment]
Okay, that makes sense, and indeed, when I create the kernel in the current thread, it doesn't consume my CPU. However, I may still be doing something wrong, because even when I call `Kernel::CheckForIncomingCommands` in my loop, the debugger hangs when I try to connect it.

**Comment by bluechill** [comment]
That comment is a little outdated.  You should also call CheckForIncomingEvents().  See the following code below which works on my machine with the debugger (it takes a couple seconds to connect).

```c++
#include <chrono>
#include <sml_Client.h>
#include <thread>

void runner()
{
	auto kernel = sml::Kernel::CreateKernelInCurrentThread(true);
	auto agent = kernel->CreateAgent("test-agent");
	while (true)
	{
		std::cerr << "Tick " << time(nullptr) << std::endl;
		agent->RunSelf(1);
		kernel->CheckForIncomingEvents();
		kernel->CheckForIncomingCommands();
		std::this_thread::sleep_for(std::chrono::seconds(1));
	}
}

int main()
{
    std::thread new_runner(runner);
    new_runner.join();

    return 0;
}
```

**Comment by adeschamps** [comment]
Thank you, that's very helpful.

What causes the delay when connecting the debugger?

**Comment by bluechill** [comment]
Probably that sleep because it does sort of a handshake to get the connect going and it's only doing one command step  and event step per second.

Alex
