### ISSUE TITLE
Invalid WME value causes segfault when printing

### ISSUE THREAD

**Issue by adeschamps** [SoarGroup/Soar#276]
This production:

```
sp "elaborate-invalid-wme
    (state <s> ^superstate nil)
-->
    (<s> ^invalid <not-a-var)
"
```

will cause a segfault when printing `S1`. Soar will print a warning about a suspicious string constant, so I don't consider this to be too serious.

**Comment by mazina** [comment]
This was fixed a while ago and will not cause a crash in the latest branch.   I just double-checked and was able to use that rule and print S1.
