### ISSUE TITLE
Should smlEVENT_AFTER_RUN_ENDS be fired when initializing agent?

### ISSUE THREAD

**Issue by adeschamps** [SoarGroup/Soar#277]
If I register for `smlEVENT_AFTER_RUN_ENDS`, and then execute `run` and `init`, then I don't receive a callback. If I need to know when the agent stops running, should I just register for `smlEVENT_AFTER_AGENT_REINITIALIZED` as well? Are there other ways in which an agent could stop running that I should be aware of?

**Comment by mazina** [comment]
From looking at the code, it should give you a callback.  I do see that if
an agent stopped because of an interrupt or if another agent needed to keep
running, it may not issue the smlEVENT_AFTER_RUN_ENDS callback for the
agent that stopped.

**Comment by mazina** [comment]
Closing.  In the future, please send question to the soar-help mailing list.
