### ISSUE TITLE
Error starting SoarJavaDebugger.jar on mac

### ISSUE THREAD

**Issue by neharajan9** [SoarGroup/Soar#278]
I tried to launch SoarJavaDebugger.jar on my mac but  every time i am unable to do so and getting this error.
[hs_err_pid872.txt](https://github.com/SoarGroup/Soar/files/1091759/hs_err_pid872.txt)

 I have java8 installed as per your recommendation and trying to launch Soar 9.4.0.

Please advice.

**Comment by mazina** [comment]
Try running it from the command line and see what it says.  It's probably a java issue, but you may also want to to try running the command-line interface to Soar to make sure.  (It's in the bin directory).

Also, where did you read that java8 is recommended for Soar 9.4.0?  It will be for Soar 9.6.0, but 9.4.0 was built with java 7.  That said, I use Soar and java 8 on my mac, for what that's worth.

**Comment by neharajan9** [comment]
Thanks mazina for your quick and effective response.
