### ISSUE TITLE
New version of Tcl doesn't work with TclSoarLib

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#286]
The latest version of tcl, in fact the only version they have from their site (since they don’t have an archive) has renamed the main dll name.  tcl86.dll -> tcl86t.dll

So if someone grabs Soar, then grabs tcl and wants to run with tcl, it will not work since tclsoarlib is looking for the wrong dll or rather linked against the wrong dll.  Which was previously the right dll, but no longer.

**Comment by Sonophoto** [comment]
is it possible this is a mistake on the tcl side? I'm trying to imagine a good reason for changing the name of the library....

Update: 
It appears that Active State tcltk and Official tcltk have diverged so possibly a correct fix can take that into account.

it looks like sometime in 2015 Active State changed their tcltk interface. At least one python tool developer says Active State Python / tcltk is incompatible: https://github.com/matplotlib/matplotlib/issues/4577 and requires a full rebuild(relink) of matplotlib to get it to work. 

These are the Official development repos for tcltk and unless I misread the tcl makefile.in it builds a "tcl86.dll"

 tcl is: https://github.com/tcltk/tcl 
  tk is: https://github.com/tcltk/tk

**Comment by marinier** [comment]
Anything is possible. The 8.6 release notes (
https://www.tcl.tk/software/tcltk/8.6.html) say that they are now creating
a threaded build by default, so the "t" suffix probably means "threaded".
But those release notes are for 8.6 generally, not 8.6.7 specifically. The
8.6.7 specific release notes (https://wiki.tcl.tk/48933) don't say anything
about changing the library name.

If TclSoarLib loads the dependency dynamically, then it can probably just
look for both file names.

**Comment by Sonophoto** [comment]
I'm under the impression that their is an FOOS tcltk and a commercial windows product (with free download) called Active State Python. I know from past experience that Active State Perl and FOOS Perl behaved differently (no-judgment).

I've seen posts from late 2015 talking about the tcl86t.dll causing problems so the file name has been in play for a bit.

I concur that recognizing that there is an alternative DLL to import tcl86 and trying "tcl86t.dll" when the first is not found would be a good immediate workaround.

**Comment by marinier** [comment]
Why was this issue closed? I don't see a commit with a fix.

**Comment by Sonophoto** [comment]
accidental, I appologize.

**Comment by Sonophoto** [comment]
The library name appears to be determined at build time in https://github.com/SoarGroup/Soar/blob/development/Tcl/SConscript (Soar/Tcl/SConscript). On windows machines lines 27 and 28 hard-code the name into the build and line 103 adds the name to the LIBS variable in the compilation command to build TclSoarLib.

So an immediate work-around should be to change the name on lines 27 and 28 and rebuild Soar. I don't have a windows build environment to test this but I hope it helps...

**Comment by garfieldnate** [comment]
Fixed in 7f598b47875afe0a6f54ee24f1cafe83bb0fefcb, which will be merged soon.

**Comment by garfieldnate** [comment]
I ended up completely re-vamping the logic for finding Tcl during building. Fixes are pushed, and CI now builds with Tcl for all three supported platforms.
