### ISSUE TITLE
Outdated documentation for RHS log command and help output

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#288]
The manual's description of the RHS log command has two issues:

* It says that the specified log level will cause the text to be written when the log level is set at that number or higher. It appears that the levels are actually all independent channels.
* It points to section 9.6.1 (trace command) for how to set the log level. It actually should point to 9.6.2 (output command).

In Soar itself, doing a "help output" shows incorrect information wrt logging -- it shows an agent-trace option that doesn't exist. "output ?" appears to show the correct information.

**Comment by Bryan-Stearns** [comment]
Good catches. Those should now be fixed in the source code side.
