### ISSUE TITLE
add #define/ifdef/ifndef/endif -like functionality to Soar

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#29]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:50:47_

Description From Bob Marinier 2008-02-28 11:29:13 (-) [reply]
Sometimes I find myself with a large group of productions that I want to 
easily
enable or disable.  I could add a flag to the top state and change every
production to test this flag, but this is a pain (and error prone, if I 
mistype
something).  A much easier solution would be to incorporate #define-like 
syntax
in Soar, so entire blocks of code can be included or excluded easily.

Syntax: Since # already has a meaning, we should probably use something 
else,
e.g., just the words define, ifdef, ifndef, and endif.  (Note that I am not
arguing for a fully functional macro language like C/C++; I just want to be
able to easily flag which blocks of code to use).  Here's a possible 
example:

define DEBUG

ifdef DEBUG
 sp {monitor*....
 ...
endif

Implementation: There are at least two ways I can see implementing this: in 
the
kernel, as a new syntax, or as commands (in which case they would be part 
of
commandline interface).  I favor the command approach for simplicity 
(changing
Soar's parser is probably hard).  Basically, the define command will keep a
list of constants that have been defined, and the ifdef/ifndef commands 
will
set CLI switches (if the test fails, ignore all commands until endif is
reached; otherwise execute commands as usual).  I suppose the switch could 
be
set in the parser directly, but telling CLI to ignore commands is probably
simpler.

Also, these do not have to all be separate commands.  There can be just one
command, e.g. define, with arguments to do all this, and the rest can just 
be
aliases.

One source of confusion for C/C++ programmers may be the fact that, in 
Soar,
# define FOO actually does NOT define FOO, since the line is commented out.

But
I think they'll get used to it (the alternative is to add special-case
processing to code to recognize the difference between a comment and a 
define,
and that sounds like a buggy situation).

There are some issues like, will we support nesting, or logical tests of 
flags?
  I say we start simple, and see what people really want as far as more 
complex
features go. 

Incidentally, this approach also gives Soar the ability to block-comment 
code,
e.g.:

ifdef COMMENT #COMMENT is not define'd anywhere
...
endif

...which is something I've wanted for a long time.

_Original issue: http://code.google.com/p/soar/issues/detail?id=28_

**Comment by mazina** [comment]
Moved to feature requests in wiki
