### ISSUE TITLE
can soar run in vxworks system which is a Real-time opterating system?

### ISSUE THREAD

**Issue by heikefn** [SoarGroup/Soar#290]
In fact ,I want to run soar in vxworks,a real-time operating system,which can run java file,so i have some questions about Portability and support.
1.Is the running soar associated with the operating system kernel?
2."Soar" runs on MAC,ubuntu, and Windows, does it involve function calls to the operating system kernel?
3.whether can run soar as long as can run java file since i saw javabugger?
4.could you gives us any site or introduce what supports run the soar file?

**Comment by mazina** [comment]
The version of Soar hosted in this github repo is written in C++ and does involve system calls.  The debugger is in java, but it is just a GUI that interfaces to C++ version of Soar.

If you'd like to run on non-Ubuntu linux, you will need to download the source code and compile yourself.  While we do not officially support other flavors of Linux, you may be able to compile it without major issues

You may also want to check out JSoar, a pure java port of Soar 9:  https://github.com/soartech/jsoar

**Comment by heikefn** [comment]
Firstly,thank you for replay,i am fengen,that chinese student.I have read Jsoar roughly but i'm afraid whether jsoar can completely replace soar.My meaning is that i see the  jsoar is still update recently and i don't konw whether  the jsoar  is mature .
