### ISSUE TITLE
Is soar a open source architecture?

### ISSUE THREAD

**Issue by heikefn** [SoarGroup/Soar#295]
I want to port soar to a embedded operator system,so I need to know weather soar is open source.

**Comment by garfieldnate** [comment]
Soar is open source, released under the BSD license (the license file is in the repository: https://github.com/SoarGroup/Soar/blob/development/LICENSE.md). Sounds like a fun project! You are not required to share any work that you do on Soar, but I hope that you do.

**Comment by heikefn** [comment]
Thank you. Do you have any datums or instruction of parse.cpp,lexeme.cpp or other *.cpp in the SOAR source code? If you have or your friends has ,please let me! @garfieldnate

**Comment by heikefn** [comment]
@garfieldnate

**Comment by garfieldnate** [comment]
I don't have any specific instructions for the cpp files; just download everything, make sure you can build it, then start hacking! To build it you'll need python and SCons (I think you can just do `pip install scons`). There are build scripts for Windows, iOS and Linux in the root directory. For your project you will probably need to customize the `Sconstruct` or other build files.

**Comment by mazina** [comment]
Yeah, what Nathan said.  There is no documentation for the source code
except for comments.

Just a small addition. Scons is included with the source code. We’ve had to
change a few minor things in scons in the past. (Those changes were to made
to support versions of java and windows that scons didn’t recognize at the
time. They may no longer be necessary with the latest version of scons.)

- Mazin
