### ISSUE TITLE
Missing references in manual

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#296]
In the most recent version of the manual posted on the Soar website contains "??" in a couple places that appear to be missing references to other sections.  For example, the end of section 2.7.4 contains this:

Negated conditions that test for the absence of working memory elements
that are local to the substate are not included, which can lead to overgeneralization in the
justification (see Section ?? on page ?? for details).

Section 3.4.1 also contains some ?? in the part describing ^quiescence.

**Comment by Bryan-Stearns** [comment]
It should be fixed now. The website linked to an outdated version of the manual different from the GitHub file. The updated version should have a draft date of Nov, 2017 instead of July, 2017.
