### ISSUE TITLE
echo --nonewline doesn't work

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#297]
In the Soar 9.6.0 release, if I do this command:

```
echo --nonewline foo
```

I get the output:
```
No such option: nonewline
```

The help for this command indicates this should work.

**Comment by mazina** [comment]
This seems to be a typo in the help file.  It's seems to actually be ```--no-newline``` and has been that way since at least 9.3.2.  I'm guessing people haven't noticed the typo b/c they just use -n.

Personally, I like --nonewline better than what it really is.

**Comment by marinier** [comment]
FWIW, in jsoar it's --nonewline. If no one noticed, then maybe it's not a
big deal to change it.
