### ISSUE TITLE
Number for epmem time

### ISSUE THREAD

**Issue by nickredsox** [SoarGroup/Soar#304]
Running the epmem tutorial I receive the following output. Is the number given for the time correct? If so what does this number correspond to? According to tutorial pdfs this is supposed to be a low integer number. I ran this tutorial and received the same output on a windows and linux computer.

-Nick D

edit:
I was using Soar 9.6 when I was getting these large numbers. I tried running on Soar 9.4 and the numbers were as expected
```



trigger is now dc
learning is now on
Now printing when episodic memory records a new episode or considers an episode in a query.

********
Total: 8 productions sourced.
run 1 --phase
run 1 --phase
New episodic memory recorded for time 140644198633240.
run 1 --phase
run 1 --phase
run 1 --phase
    24: O: O1 (init)
run 1 --phase
run 1 --phase
New episodic memory recorded for time 140644198633240.
run 1 --phase
run 1 --phase
run 1 --phase
    25: O: O2 (cbr)
run 1 --phase
run 1 --phase
New episodic memory recorded for time 140644198633240.
Considering episode (time, cardinality, score) (140644198631592, 0, 0.000000)
Considering episode (time, cardinality, score) (140644198631592, 4, 0.000000)
NEW KING (perfect, graph-match): (false, false)
Considering episode (time, cardinality, score) (140644198631592, 0, 0.000000)
```

**Comment by mazina** [comment]
Thanks for the report.  We think we know why that's printing incorrectly.  Steven is working on a fix.

**Comment by scijones** [comment]
Alright, I think I have a fix. I have pushed to the development branch and it should be resolved. There was an issue where the change we made to printing accidentally attempted to pass a va_list as a variadic argument, which is not allowed. I hacked a different function in and now it should work.
