### ISSUE TITLE
Soar Java Debugger decision cycle graphic no longer shows correct stop phase

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#307]
In the Soar Java Debugger, the decision cycle graphic has a red marker that is supposed to show the current stop phase. It no longer shows the correct stop phase at startup or when it is changed. My guess is that behind the scenes it's trying to run a command, and that this wasn't changed to match the new command structure?

**Comment by garfieldnate** [comment]
This was fixed in 9.6.1.
