### ISSUE TITLE
Change "soar stop-phase proposal" to "soar stop-phase propose"

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#308]
For some reason, in the `soar stop-phase` command, the name of the propose phase was changed to `proposal`. This seems like a mistake? If it's not a mistake, I guess you can disregard this, but the change doesn't make sense to me.

**Comment by mazina** [comment]
As far as I can tell, this has always been proposal.  (At least, it was as far back as 9.3.2.)

I do agree that "propose" makes more sense given the names used for the other phases.  I'll change to a feature request.

**Comment by marinier** [comment]
Interesting. In jsoar it's propose, and given that most of jsoar was directly ported from csoar, I wonder if it changed at some point. That said, the jsoar stuff was originally written 10 years ago, so lots could have changed in the meantime :)

**Comment by garfieldnate** [comment]
Even after fixing this the command is not consistent because `apply` is still a verb while the others are nouns. `application` would fit better. But I'll leave that alone.
