### ISSUE TITLE
soar stop-phase description is cut off in help command output

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#309]
If I do `soar ?` I get the expected output; in particular, the blurb about stop-phase looks like this:

```
stop-phase                                apply    Phase before which Soar will stop
```

But if I do `help soar`, in the subcommand summary near the top, the description of the stop-phase appears to be cut off:

```
stop-phase                                apply    Phase before which Soar
```

**Comment by mazina** [comment]
This seems to already be fixed in the current development branch.
