### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by aaronang** [SoarGroup/Soar#312]
If I understood correctly, Python 3 is not supported due to SWIG. However, since the release of SWIG 3.0, SOAR should be able to support Python 3. I think that supporting Python 3 is mandatory unless support for Python is dropped. Python 2 will be deprecated in 2020.

I would love to help out but might need some guidance 😄

**Comment by mazina** [comment]
While the scons script will, by default, build an interface for python 2.7, it can also build them for python 3.  To do that, you just need to specify your python 3 path when you run the scons build script via the --python option.

**Comment by aaronang** [comment]
@mazina Thank you for your reply. Are there any plans for defaulting to Python 3 since Python 2 is going to be deprecated in 2020? Are there plans for making releases that by default include Python 3 modules instead of Python 2?

**Comment by mazina** [comment]
We do plan to switch over for the next release.
