### ISSUE TITLE
Unable to build soar using python scons/scons.py all

### ISSUE THREAD

**Issue by saumilsdk** [SoarGroup/Soar#318]
Build logs:

Building intermediates to build
Installing targets to /home/ubuntu/projects/Soar/out
Tcl headers and libraries not found at /opt/ActiveTcl-8.6, not building TclSoarLib.
Checking for C library GL... (cached) no
Checking for C library GLU... (cached) no
Checking for glXGetProcAddressARB("") in C library GL... (cached) no
Checking for glXGetProcAddress("") in C library GL... (cached) no
Checking for glXGetProcAddressEXT("") in C library GL... (cached) no
Cannot find GL, GLU, not building svs_viewer
Tcl headers and libraries not found at /opt/ActiveTcl-8.6, not building Tcl SML wrappers.
C# compiler not found, not building C# SML wrappers
scons: done reading SConscript files.
scons: Building targets ...
Making build/Core/CLI/src/cli_soar.os
Making build/Core/libSoar.so
Install file: "build/Core/libSoar.so" as "out/libSoar.so"
Making build/UnitTests/UnitTests
late_java_builder(["fake_java_target"], [])
Making build/Core/ClientSMLSWIG/Java/sml.jar
sh: 1: jar: not found
scons: *** [build/Core/ClientSMLSWIG/Java/sml.jar] Error 127
scons: building terminated because of errors.

**Comment by mazina** [comment]
That's not much to go on, but it looks like it compiled the main Soar binary correctly but failed on the java interface.  I'd try to keep what you've already built and issue the exact same build command again.   Sometimes the java part of the scons script fails b/c of a timing issue.  (The java target is set up in a weird delayed way that can fail if something else doesn't happen in time.  I'm not sure why;  it was designed before my time, and I don't know what the original issue was that led to that design.)  

P.S. Please use the Soar help mailing list for any questions like this in future.  You can find instructions on how to sign up at soar.eecs.umich.edu.

**Comment by saumilsdk** [comment]
I tried running the same build command multiple times but no change. It fails on the same error. What things are not building after that error?
