### ISSUE TITLE
can't build Soar

### ISSUE THREAD

**Issue by medhaja** [SoarGroup/Soar#320]
Hi,
I am newbie to Soar Architecture. Trying to build Soar but i am not able to build it. kindly resolve the issue.
OS : windows 7
![soar](https://user-images.githubusercontent.com/24703503/68282962-a585d400-00a0-11ea-9e23-24d38ed9786d.PNG)

**Comment by mazina** [comment]
My guess is that you either have a basic problem with your visual studio install or you're using a new version of visual studio that the older version of scons bundled with Soar does not recognize.

I'd suggest posting help questions of this sort to the soar mailing list.  (Instructions for signing up is at soar.eecs.umich.edu.)   There may be someone on there with more Windows experience who can help you with this.
