### ISSUE TITLE
input capture loses double digits of precision

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#331]
The `save percepts` command captures WME changes to a file. When the WME is a double, the file does not capture the full digits. This can result in a replay of that input causing different behavior than originally occurred in the system (e.g., because the original value changed, but the recorded value does not change due to loss of precision). Here's a concrete example: the number of seconds since the epoch (captured as a double to get fractional seconds) cannot be sufficiently represented in the current system, resulting in this time value appearing to never change in the playback, even though it was changing fine in the original run when the recording took place.

The issue appears to be in `Core/KernelSML/src/sml_AgentSML.cpp`, in the method `AgentSML::AddDoubleInputWME`. The double value is captured like this:

```cpp
std::stringstream valueString;
valueString << value;
```

By default, this does not capture the full double precision. To capture the full precision, the [internet tells me](https://stackoverflow.com/questions/12894824/double-and-stringstream-formatting) you need to do something like this:

```cpp
std::stringstream valueString;
valueString << std::setprecision(std::numeric_limits<double>::digits10 + 1) << value;
```

There are other options, too (e.g., using fixed-point notation instead of scientific notation may be easier to read for those manually inspecting the file).

**Comment by marinier** [comment]
Also, and this is a very minor point, you really only need an `ostringstream` not a `stringstream` -- using an `ostringstream` would prevent you from accidentally using `>>` when you only use this object to do `<<`. I don't know if there are any other benefits in terms of memory or performance, but probably not much if at all.

**Comment by garfieldnate** [comment]
As per newer comment from Catree, I think it should be fine to use 

    valueString << std::setprecision(std::numeric_limits<double>::max_digits10) << value;

**Comment by garfieldnate** [comment]
I committed the fix on a branch and there's a build you can try [here](https://github.com/SoarGroup/Soar/actions/runs/3731779490). As much as I hate to say it, I don't know a quick way to automate a test for this and I'm not sure I'll be able to get to it. Would you mind downloading the binary and testing with your data? The artifact named "Soar-linux" is actually the Windows one. I misnamed it.

**Comment by marinier** [comment]
For some reason the soar-linux artifact refuses to download. But I built everything myself anyway. Unfortunately, I don't have easy access to the code that we originally ran into this problem with (it wasn't my code). I'll see if I can get someone else to try it.

As far as automated testing goes, I guess the question is what exactly would we be testing? If we wanted to confirm that playback actually worked correctly, that seems hard. But an easier thing to do would be to see if the file is generated as expected. So the test would be:
* Record inputs. No rules are necessary.
* Put a double WME on the input-link
* Read the generated file (in C++, not Soar) and confirm that the double value matches what was put there. If the full precision was captured, then it should match exactly.
