### ISSUE TITLE
remove duplicate constants from sml_Names

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#34]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:58:04_

Description From Bob Marinier 2008-06-13 13:55:07 (-) [reply]
Some of the constants contained in sml::sml_Names (sml_Names.h in
ConnectionSML) are redundant with constants contained in soar_TraceNames
(soar_TraceNames.h in shared).  These should be removed from sml_Names in 
order
for it to be clear which constants are used by the kernel vs. the ones used
exclusively by SML.

_Original issue: http://code.google.com/p/soar/issues/detail?id=33_

**Comment by mazina** [comment]
Moved to suggestions/feature-requests
