### ISSUE TITLE
Incorrect error message for capitalize-symbol RHS function

### ISSUE THREAD

**Issue by marinier** [SoarGroup/Soar#342]
CSoar 9.6.0
Windows 10
x64

The `capitalize-symbol` RHS function expects a single string argument.

If I try to load this rule (with two arguments):
```
sp "test
(state <s> ^superstate nil)
-->
(write (crlf) (capitalize-symbol foo bar))
"
```
The error message says:
```
Wrong number of arguments to function capitalize-symbol (expected 206158430209)
(Ignoring production test)
```
Maybe the variable for the number of expected args didn't get initialized?

Furthermore, if I pass in a non-string, like this:

```
sp "test
(state <s> ^superstate nil)
-->
(write (crlf) (capitalize-symbol 1))
"
```

There is no error message at runtime -- it just silently fails. This is not returning an empty string, as if the `write` is printing other things, then nothing gets printed at all in this case. (Same if the arg is a float or an identifier.) Personally I think it should try to capitalize anything that gets passed to it and return the result as a string, and if that thing isn't a string it just returns the number (as a string). But at least the current behavior should print an error at runtime. Note this may be a more general problem (e.g., calling `/` with 0 as the second argument also silently fails).

**Comment by garfieldnate** [comment]
The behavior on development looks fine to me.

```soar
sp {test-bad-arg
(state <s> ^superstate nil)
-->
(write (crlf) (capitalize-symbol 1))
}
step 1
```

Prints `Error: non-symbol (1) passed to capitalize-symbol function.`

```soar
sp {test-too-many-args
(state <s> ^superstate nil)
-->
(write (crlf) (capitalize-symbol foo bar))
}
```
Prints:
```
Wrong number of arguments to function capitalize-symbol (expected 1)
(Ignoring production test-too-many-args)

Production addition failed.
```

```soar
sp {test-correct
(state <s> ^superstate nil)
-->
(write (crlf) (capitalize-symbol foo))
}
step 1
```

Prints `Foo` (it works correctly).

I had to change out the quotes for `{}` in your examples because the quoted productions can't be sourced via the regular `soar` command line. I'm not sure what the correct context for using those is (have to use the debugger?).

If the behavior described above seems fine to you, feel free to close this.

**Comment by marinier** [comment]
I just rebuilt the latest on windows and tested in the Soar Java Debugger, and I'm still getting a very large number for the number of expected arguments. Maybe it's an issue with the Java interface (if the wrong type is used, this sort of thing could easily happen -- could be an int vs. long thing).

The double quotes should be directly supported in the normal parser. They work fine in the Soar Java Debugger, and it's important that they work in general. Most code at ST uses quotes, because they are necessary in Tcl (quotes vs. braces has a special meaning in Tcl). Maybe it's just the command line soar that doesn't understand them.

(BTW, the command line Soar still says 9.6.0 at startup.)

**Comment by marinier** [comment]
I tried it from the command line Soar on windows and got the same problem:

```
soar % sp {test
(state <s> ^superstate nil)
-->
(write (crlf) (capitalize-symbol foo bar))}
Wrong number of arguments to function capitalize-symbol (expected 927712935937)
(Ignoring production test)

Production addition failed.
```

Perhaps this is specific to the windows build. At least it doesn't appear to be a Java issue.

**Comment by marinier** [comment]
Regarding why quotes don't work in the soar command line application, it appears that the issue is in `soar_cli.h`, in the `totalnesting` function. It checks for `{`, `}`, and `|`, but doesn't check for quotes. The way this is structured might make it hard to add support for quotes correctly, because it assumes that braces are the only character that needs to be matched -- e.g., if we merely added quotes like braces, then you could use a quote to start a rule and a brace to finish it. I think this is probably not worth addressing for this simple application (and sourcing a file that has rules with quotes in it should still work fine -- this only affects typing directly on the command line).

**Comment by marinier** [comment]
So, it appears that the bug with the strange number getting printed for the expected number of args has to do with how it is passed to the string conversion. In `parser.cpp` line 1522, it says:

```cpp
thisAgent->outputManager->printa_sf(thisAgent,  "Wrong number of arguments to function %s (expected %d)\n",
              rf->name->sc->name, rf->num_args_expected);
```
This eventually makes it's way to `output_print.cpp` line 319, which handles the `%d` in the format string like this:

```cpp
destString += std::to_string(va_arg(args, int64_t));
```
If we look at the [documentation for va_arg](https://cplusplus.com/reference/cstdarg/va_arg/) we see that it says:

> For a type expression to be suitable for its use with va_arg, it must be such that type* produces a pointer to type.

I'm pretty sure this is not the case here, because the value passed in originally, `rf->num_args_expected` is an `int`. So I think it tries to access the memory location of an `int` as an `int64_t`, and the extra bits past the end of the int get read and interpreted -- at least on windows! Note because this appears to be happening via a pointer, there's no automatic casting going on.

If we cast explicitly, then it seems to work (on windows):
```cpp
int64_t numArgs = rf->num_args_expected;
thisAgent->outputManager->printa_sf(thisAgent,  "Wrong number of arguments to function %s (expected %d)\n",
      rf->name->sc->name, numArgs);
```
(As implied by the fix, this problem was not specific to this particular RHS function -- it would happen with any of them.)

**Comment by garfieldnate** [comment]
Thank you for looking into this! This is undefined behavior, then. It just happened not to do anything bad on my computer.

`va_arg` is inherently unsafe, and this is essentially stringy-typing with no help from an IDE possible; `%d`, `%u` and `f` are `int`, `unsigned int` and `float` (usually all 32-bits) in standard lib functions, but in Soar's own output function they have been used for strictly 64-bit types, so this is a footgun. I do see a correct usage with a cast in cli_preferences.cpp, line 181, so I'm hoping this isn't a problem everywhere in the codebase. I'll take a look around.
