### ISSUE TITLE
debugger text difficult to read with dark mode on

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#352]
It sort of looks okay in this image, but the debugger default font is black and tiny, which is very difficult to read when dark mode is on (using M1 MacOS 13.1). I was able to find font settings and could change the size, but changing the color in the menu did not change the color of the Soar code shown here. The "Filters" text is very difficult to read, as well.
<img width="510" alt="Screenshot 2022-12-21 at 11 27 47 PM" src="https://user-images.githubusercontent.com/778453/209014653-e879bf16-d341-43aa-9ca2-b25dac474292.png">

**Comment by marinier** [comment]
One thing to check is if we're using the latest swt (4.26 came out last
month). It might make a difference (and it's best to be on the latest
anyway).

**Comment by garfieldnate** [comment]
This is actually using the latest SWT (had to add it to run on an M1 Mac).

**Comment by garfieldnate** [comment]
Since light mode is still quite readable, it would be a nice solution to just force the application into light mode, but this is not supported by SWT. We can, however, detect if dark mode is active via `Display.isSystemDarkTheme()`. This actually means different things on different systems, though, so any styling done based on this would need to be tested across platforms.

**Comment by jakbtg** [comment]
I have the same issue on my mac with Intel. 
Also the small + icon on the left completely disappears in dark mode.
![Screenshot 2023-06-20 alle 23 21 42](https://github.com/SoarGroup/Soar/assets/65966285/5758a844-83e7-45da-bea3-ded563abda06)
![Screenshot 2023-06-20 alle 23 25 44](https://github.com/SoarGroup/Soar/assets/65966285/fe174bb8-3319-4129-b59f-02d4b2c7d0fe)
