### ISSUE TITLE
Version 9.6.1 Visual Soar JVM error

### ISSUE THREAD

**Issue by FelipeMarra** [SoarGroup/Soar#357]
VisualSoar.bat is not opening in my computer:
System Type	64 bits operating system, x64 based processor
Edition	Windows 10 Home
Version	22H2
OS Build	19045.2364

Java Version 8 (build 1.8.0_351-b10)
JDK Version 17.0.5

Version 9.6.0 works fine. Version 9.6.1 presents the following error:

![Captura de tela 2023-01-05 182300](https://user-images.githubusercontent.com/89817439/210882549-793899da-cae9-4d81-bbdf-a5ba8ba18ff7.png)

After clicking ok:
![Captura de tela 2023-01-05 182343](https://user-images.githubusercontent.com/89817439/210882628-38a44f69-a006-4385-b3c1-45746ab81b3e.png)

**Comment by garfieldnate** [comment]
We updated the required Java version with this release. You need to have Java version 11 or higher.

**Comment by FelipeMarra** [comment]
Bro Java env is such a mess 😪😪😪 installed amazon corretto 11 and it is now working... thanks and sorry for the inconvenience

**Comment by garfieldnate** [comment]
No problem :) Java 11 is from 2018, and you don't need to limit yourself to that version. The current LTS is 17, which works fine with Soar (we tested it during the release). I recommend using [sdkman](https://sdkman.io/) to manage Java versions.
