### ISSUE TITLE
Soar Tutorial Part 2 PDF with missing texts in red boxes since page 27 (72)

### ISSUE THREAD

**Issue by rgudwin** [SoarGroup/Soar#360]
This bug is happening since version 9.6.0 and persists still in 9.6.1. In Soar Tutorial Part 2 PDF, the red boxes pointing to important parts of figures are empty, or with the text located in random positions, after page 27 (or 72 in print). Up to page 27, there is no error. The errors start from page 27 onward. There seems to be a problem in the PDF generation. In version 9.5.0 it doesn't occur. 
![image](https://user-images.githubusercontent.com/7912248/225435348-564dc828-aac4-47c2-a59f-6e4a5438fefa.png)

**Comment by scijones** [comment]
Well, that's not great. Thanks for the report!

**Comment by scijones** [comment]
This is not a great solution, but for right now if you go here: https://github.com/SoarGroup/Release-Support/tree/master/SoarTutorial -- those files have appropriately aligned text and non-empty boxes.

**Comment by garfieldnate** [comment]
Closed via [SoarGroup/Release-Support/f24e8013e5b69bd5a2705faeede2707fe8fbcac5](https://github.com/SoarGroup/Release-Support/commit/f24e8013e5b69bd5a2705faeede2707fe8fbcac5). Thanks for reporting!
