### ISSUE TITLE
watch trace 5 not showing in debugger

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#366]
`Watch 5` button in the debugger should show updated preferences and working memory changes, but on this is not showing at all. The info is still visible from the CLI, so it's a debugger issue.

**Comment by marinier** [comment]
This actually might not be a debugger issue. First, by default the debugger hides higher-level trace information and you have to click the + icons in the left margin of the trace window to show it for some segment of the trace. There is also the Expand button below the trace.

Second, the mechanism used by the Java debugger to get the trace information is different than what CLI uses, and it may be that this mechanism is broken in Soar. Specifically, the CLI gets straight text, but the Java debugger uses the XML structured output (so it knows what the different parts of the trace are and can hide them). If the XML is no longer being generated on the Soar side, or somehow is broken, that could lead to some trace information not showing up.

Or of course the debugger could actually be broken :)

**Comment by garfieldnate** [comment]
I believe this was fixed in 083aa4492565e5edb29d033987dfe9e0e569a935, the actual issue being that users with dark mode can't see the little `+` icons that let you expand the trace 5 logs.
