### ISSUE TITLE
smem --clear throws error if run first thing

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#370]
We have an agent that uses smem. It seems reasonable to add this to the beginning of the sources to initialize smem, either when we first load the agent or when we re-load the agent:

```soar
smem --enable
smem --clear
```

The first time you run this, the `clear` command will error out and prevent the rest of the `source` command from continuing!

From the source, it looks like the smem DB is connected to lazily, and `–clear` is not one of the commands that triggers loading the DB. Users instead need to do an add of some kind before the DB connection is actually created. Even `smem –init` does not initialize the DB unless it has already been initialized once.

**Comment by garfieldnate** [comment]
Epmem has different parameters: `--enable` and `--init`. It does not put off connecting to the DB until actual episodes are added (probably because they are guaranteed to be added), and does not suffer from this issue.

**Comment by garfieldnate** [comment]
I went with a fix that connects to the DB in `smem --init`. I'll leave the PR open for a bit in case there are any concerns.

**Comment by scijones** [comment]
I've hacked on SMem quite a bit and for what it's worth, that change makes sense to me.
