### ISSUE TITLE
Debugger scrolling weirdness

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#383]
The debugger tries to scroll intelligently, sometimes sticking to where the user has scrolled to, and sometimes auto-scrolling to the bottom when new output is available.

Steven (and others) report intermittent issues:

1. Sometimes the debugger seems to save your place when you scroll up. When you then scroll to the bottom and some output occurs, it auto-scrolls you back up to where you were before. Incredibly annoying.
2. When the debugger is stuck in the mode where it doesn't follow output, you can do a single step in it to reset to output-following mode.

My preferred solution here is to add a toggle somewhere that turns on/off output-following. The proper rules for automatically determining this are not clear to me and are probably subject to personal preference, so I would rather just let the user decide.

**Comment by garfieldnate** [comment]
Note from Bob W. about 9.6.2 debugger scrolling regression:

> The 9.6.2 debugger consistently fills up a screen of text and then stops scrolling. Hitting "Stop" will bounce the display to the bottom.

**Comment by marinier** [comment]
The scrolling is intended to stop if you click somewhere, and then if you
move the cursor to the end (e.g., ctrl+end), then the scrolling should
follow the trace again. If that's not happening, try testing it on all the
major platforms to set if the issue is platform specific. Maybe the swt
libraries need to be updated.

**Comment by garfieldnate** [comment]
The 962 text box has a blinking caret, while the 961 one does not. Not sure if that matters; it's actually useful for understanding the behavior of the window.

It looks to me like the 961 debugger tries to scroll the (invisible) caret to the center of the window, while the 962 debugger tries to scroll the (visible) caret to the top. So clicking around causes the window to scroll, and when the user tries to scroll themselves, the input is quickly overridden. This is all happening while there's continual printing in this window. The print events to the window reset the scrolling.

The logic is over here: https://github.com/SoarGroup/Soar/blob/development/Java/Debugger/src/edu/umich/soar/debugger/helpers/FoldingText.java#L1129.

Also, according to [this](https://stackoverflow.com/questions/3047982/java-swt-text-swt-multi-append-text-without-scroll#comment3135032_3054203) comment, we don't need special logic to *prevent* StyledText from scrolling, because by default it does not scroll. We switched from Text to StyledText, so we have to update the scrolling logic to match it.

**Comment by garfieldnate** [comment]
Fixed in 294be2c03d8cff455da9a0ecc850b5a456caf45d.
