### ISSUE TITLE
Soar has no numeric equality operator

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#42]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 01:05:47_

Description From Sam Wintermute 2008-09-10 12:31:18 (-) [reply]
Soar has numeric tests for >,<,<=,>=, but not plain equality. This is
apparently because that should be handled by just matching values, but that
does not work when one number is internally an integer and the other is
internally a float. So, Soar can detect that 1 <= 1.0 and 1 >= 1.0, but 1 
!=
1.0 as detected by matching.

There should be a operator for equality across ints and floats, or the 
matcher
should do implicit conversions, since these types are hidden from the user, 
and
for symmetry with the rest of the numeric tests. If this isn't done, the 
manual
should be updated to note this when the comparison operators are discussed.

_Original issue: http://code.google.com/p/soar/issues/detail?id=41_

**Comment by mazina** [comment]
Moved to feature requests in wiki
