### ISSUE TITLE
soar client error failed to create a window

### ISSUE THREAD

**Issue by ayman823** [SoarGroup/Soar#433]
pls fix this error for me soar client error:failed to create a window

**Comment by garfieldnate** [comment]
Please tell me:
* your OS
* your Soar version
* what you did that triggered the error
* more details about the error. Is this message printed in the debugger? In your terminal?

**Comment by garfieldnate** [comment]
I cannot reproduce your issue without further details, so I'm going to close this.

**Comment by Sfifteen12** [comment]
can u tell me how to fix same issue here

**Comment by garfieldnate** [comment]
@Sfifteen12 Is this your issue? https://github.com/SoarGroup/Soar/issues/502

**Comment by noxuafk** [comment]
o meu deu o mesmo erro e eu só instalei e tentei abrir

**Comment by brightindarkness** [comment]
This is my issue too
Please tell how can i fix it

**Comment by garfieldnate** [comment]
@brightindarkness This is not the Minecraft Soar project, in case that's what you were looking for.

**Comment by Sfifteen12** [comment]
yea its been time since i quit mc bro also thanks
