### ISSUE TITLE
save/load epmem

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/Soar#440]
It would be convenient to be able to save and load the epmem database between Soar runs.

This would also serve as a stepping stone towards full state saving and loading, which would be a very helpful feature for long-running agents.

**Comment by marinier** [comment]
Can't you already do this via `epmem --backup` (to save) and `epmem --set path <path to db>` (for load)? In fact, if you set the path, it will save, too (the backup option is really if you have an in-memory db or want to save to a different file).

**Comment by garfieldnate** [comment]
You're right, I should have checked the manual 🤦  Thank you!
