### ISSUE TITLE
Review and update these chunking unit tests

### ISSUE THREAD

**Issue by scijones** [SoarGroup/Soar#443]
For these tests, it's not trivial to say what the correct chunks are with a quick glance. they need to be reviewed in light of the change to make the setting "automatically-create-singletons" "on" by default.

Teach_Soar_90_Games
Demo_ToH_Recursive (probably worth just omitting this test from usual unit testing or rewriting the agent for this test)
Operator_Selection_Knowledge (AKA Operator_Selection_Knowledge_Mega_Test)
Constraint_Prop_from_Base_Conds

Currently, those tests simply use the command "chunk automatically-create-singletons off" to make them work (and in the case of 90 games, even that doesn't work, but that test was also already left with a comment that it wasn't working properly before my changes to create this new command.)

**Comment by garfieldnate** [comment]
Do you think that these chunks were actually reviewed in the first place? For tests that generate large sets of data, it's fairly common to just say "what we have right now is probably fine" and then add the test simply to detect unintended changes.

**Comment by scijones** [comment]
They probably weren't reviewed. But, for example, that means I want someone who knows what the 90 games agent should do to verify that it still does the right thing. Then, we could just again store the chunks and say "what we have right now is probably fine" again. I'm just not that guy.

**Comment by garfieldnate** [comment]
The guy would be @jrkirk, right?

**Comment by scijones** [comment]
Yes.
