### ISSUE TITLE
MacOS Builds broke due to `-latest` upgrade

### ISSUE THREAD

**Issue by ShadowJonathan** [SoarGroup/Soar#449]
Noting this, as I'm currently also looking at it to get #448 working on mac;

The latest working run is [this one](https://github.com/SoarGroup/Soar/actions/runs/8778798103/job/24085824230)

The next failing run is [this one](https://github.com/SoarGroup/Soar/actions/runs/8873584735/job/24359650067)

Notable is how the runner version changed, plus OS info:

Before:
```
Current runner version: '2.315.0'
Operating System
  macOS
  12.7.4
  21H1123
Runner Image
  Image: macos-12
  Version: 20240412.2
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20240412.2/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240412.2
```

After:
```
Current runner version: '2.316.0'
Operating System
  macOS
  14.4.1
  23E224
Runner Image
  Image: macos-14-arm64
  Version: 20240422.3
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3
```

**Comment by garfieldnate** [comment]
Yes this made me sad to see T_T The build fails because there's no Tcl, and the build output also says there's no SWIG. The weird thing is, though, that these changes were not made to the Ubuntu or Windows images, and also the removal of SWIG and Tcl are not mentioned in the changelog: https://github.com/actions/runner/releases.

I guess I'll open a ticket with GitHub.

**Comment by ShadowJonathan** [comment]
SWIG is not mentioned in the list of tools in the macos 13 and 14 image, even if it is in the macos 12 image, FWIW

**Comment by garfieldnate** [comment]
Thanks for the help! Should be all fixed now.
