### ISSUE TITLE
crash with O_REJECTS_FIRST and DEBUG_MEMORY

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#46]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 01:09:09_

Description From Jonathan Voigt 2009-01-08 10:48:44 (-) [reply]
From Bob's email, verbatim:

I've been working on my emo2 branch, which is up-to-date with the latest
changes from the trunk. It works well most of the time, but when I try to 
run
my thesis system with the DEBUG_MEMORY #define turned on (which clears 
memory
returned to the pools), I get a crash under the following conditions:

- this message appears in the trace: "inner elaboration loop finished but 
not
at quiescence."
- the system is trying to assert a preference for this rule:

sp {apply*operator*remove-command
   (state <s> ^operator.actions
              ^io.output-link <ol>)
   (<ol> ^<att> <value>)
   (<value> ^status complete)
-->
   (<ol> ^<att> <value> -)}

Stepping through the code, what appears to happen is this preference (among
others) gets put on thisAgent->newly_created_instantiations during
create_instantiation, as does justification-11 (during 
chunk_instantiation),
the justification associated with the above rule. Going into
assert_new_preferences, the preference for justification-11 is at the head 
of
the newly_created_instantiations list.

assert_new_preferences does a two-pass algorithm: first it goes through the
newly_created_instantiations list and puts any reject preferences 
associated
with these instantiations on an o_rejects list (the instantiations are 
still on
the newly_created_instantiations list). These preferences are then 
processed,
which possibly includes deallocating them. When a preference is 
deallocated,
the associated instantiation may also be deallocated.

Next, the items on the newly_created_instantiations list are processed, and
this is where we get a crash. It appears that the instance associated with
justification-11 got deallocated, and thus the head of the
newly_created_instantiations list is bad. The code apparently expects the
o_reject stuff to still be in this list, since it checks for them and 
ignores
them (presumably since they've already been processed). 

Interestingly, if I turn off DEBUG_MEMORY, then it's the instance 
associated
with the rule that is at the head of the list instead of the justification.
This appears to be a side effect of the deallocation (the address changes 
in
free_with_pool).

Anyway, it's amazing this works at all. I'm not sure if the instance is
supposed to be deallocated or not, but maybe it makes sense, since the 
instance
only has one pref (to remove something), and it's already been processed, 
so we
don't need the instance anymore. In that case, perhaps the right fix is to
splice any instances we deallocate out of the newly_created_instantiations 
list
(although that seems inefficient, as we have to find it in the list first, 
if
it's even there). Another possibility is to delay deallocating the 
preferences
until after all of the instances have been processed. This would mean doing 
a
third pass (albeit just over the o_rejects list).

As this last approach is the simplest, I tried it and it seems to fix the
crash. Unfortunately, it also appears to break init-soar (lots of leaked 
ids
reported, even in the water-jug demo, which doesn't have any 
justifications).

Finally, I don't know how to reproduce the crash in a simple example. It's
possible it's related to the new waterfall changes somehow. Finally, I 
can't
guarantee it isn't related to my emotion code, since I can't run my system
outside of my branch. I'm not sure what next steps to take.

_Original issue: http://code.google.com/p/soar/issues/detail?id=45_

**Comment by mazina** [comment]
Could not recreate/verify.  There have been changes made to how preferences are cleaned up, so please re-submit if still exists.
