### ISSUE TITLE
soar client failed to create a window, it cannot be executed by your computer

### ISSUE THREAD

**Issue by oldroot-nog** [SoarGroup/Soar#495]
after installing the soar launcher, I tried launching it and when I did, I get this following error
![error](https://github.com/user-attachments/assets/58e94761-fb08-4e73-a69b-1a67ba6bca12)

**Comment by garfieldnate** [comment]
What file exactly did you download? 
What file within the downloaded zip did you try to run? How exactly did you run it?
What is your operating system and operating system version?

**Comment by garfieldnate** [comment]
I'm sorry, I need more details. I'm closing for now, but reach out with details if you'd like guidance.
