### ISSUE TITLE
Security issues with dylib and jar files on MacOS (Sonoma)

### ISSUE THREAD

**Issue by analog-cbarber** [SoarGroup/Soar#498]
I downloaded SoarSuite_9.6.3-Multiplatform from https://github.com/SoarGroup/Soar/releases/tag/releases%2F9.6.3
to my MacOS M1 running Sonoma 14.3.1.

I found that the security on the Mac prevents loading of the dylib and jars preventing code from running properly.

In order to get it to work, I had to manually open each jar and dylib from the Finder and grant permission.

I don't know if there is any easier command line way to accomplish the same thing, but it obviously would be nicer if there was a better way to install this that didn't result in this issue.

**Comment by garfieldnate** [comment]
When did you download it? I had to re-upload the release in August after fixing the unquarantine logic.

Did you try to run/use Soar without first running one of the applications via the bundled .sh files? Soar will only be setup properly after you run one of the .sh files for the first time. You should see some output like this:

    First time initialization of Soar for Mac OSX ARM64...
    macOS setup: removing quarantine attributes from Soar binaries...

The setup logic that performs the unquartining is in setup.sh. If the above questions didn't lead to a resolution, then I need to see the output of that. Could you try re-downloading, unzipping somewhere, and then running `TRACE=1 ./setup.sh` in the unzipped directory, and then send me the output?

**Comment by analog-cbarber** [comment]
I downloaded this on August 7th. I just tried again and ran setup.sh and it seems to be ok.

**Comment by garfieldnate** [comment]
Thank you and sorry for the inconvenience! I haven't actually announced the release yet so I wasn't expecting many installs yet.
