### ISSUE TITLE
move to full 64-bit support

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#50]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 01:14:30_

Many kernel data structures are still in 32 bits that could be 64 bits, such 
as
the hash tables. These things need to be moved to 64 bits.

_Original issue: http://code.google.com/p/soar/issues/detail?id=49_

**Comment by mazina** [comment]
Moved to feature requests/suggestions...
