### ISSUE TITLE
Soar Not Launching 

### ISSUE THREAD

**Issue by Atharva-Tiwari12** [SoarGroup/Soar#519]
So a couple months ago i tried to launch soar and it showed me white screen while launching like the phase where the logo appears and that white screen was endless i tried reaching out discord mods and they said they could not find any root cause even after looking at the logs and unfortunately i had to leave soar but today i reinstalled it and now when i click launch it says downloading then updating then launching and closes and never rly launches i tried lookin logs but no new logs were created

**Comment by garfieldnate** [comment]
That doesn't sound like Soar at all. Are you launching the debugger? There's no splash screen. There are no logs. There is no discord community. I think you're talking about a different project.

**Comment by Atharva-Tiwari12** [comment]
nahh bro i know what i am doin but soar aint workin for now so i now i use cm client but i ll keep tryin

**Comment by Atharva-Tiwari12** [comment]
> That doesn't sound like Soar at all. Are you launching the debugger? There's no splash screen. There are no logs. There is no discord community. I think you're talking about a different project.

im sorry brother i mistakenly opened this issue here i was talking bout soar launcher which launches a minecraft (a game) instance
