### ISSUE TITLE
preferences command should be explicit about goal levels

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#55]
_From [sam.wint...@gmail.com](https://code.google.com/u/117962242458139004263/) on October 01, 2009 12:14:14_

WMEs can be linked to many states, but preferences for WMEs are handled on
a per-state basis. However, the preferences command does not reflect this.
Sometimes a WME has preferences (and hence different support) at multiple
levels, but there is no easy way to tell this. For example, see the
attached agent.

The agent goes into a tie impasse, and tries to break the tie by
determining values of operators. After performing an eval operator within
the tie, O2 gets a value, and pref o2 value shows:

  (O2 ^value 1)  :O 

Which may seem OK to the user, but the tie keeps reforming, since what is
really happening is the WME has o support in the subgoal, but no support at
top-state. This is because the justification for it at top-state (which
would normally give it i-support) has retracted. Comment out the noted line
in the source to see this. Now, pref o2 value shows:

  (O2 ^value 1)  :I 
  (O2 ^value 1)  :O 

The WME has different support at different levels, the pref command should
tell the user this. It should also ideally tell the user if a WME is linked
to a state, but has no support there.

**Attachment:** [preferences.soar](http://code.google.com/p/soar/issues/detail?id=54)

_Original issue: http://code.google.com/p/soar/issues/detail?id=54_

**Comment by mazina** [comment]
Latest version prints levels with prefs for both trace -r and the cli preferences command
