### ISSUE TITLE
item-count WMEs need better justifications

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#57]
_From [sam.wint...@gmail.com](https://code.google.com/u/117962242458139004263/) on October 27, 2009 09:43:22_

The justifications for item-count WMEs that are now
present in all tie impasses are incomplete. This can be seen by elaborating
the item-count to the top-state as a result of a tie. The
justification of the result is too
general-- e.g., "if there is a top-state, there are 5
tied operators". This is because backtracing cannot trace through
the item-count WME.

I implemented a partial fix for this (that works for my agent), by adding a
fake preference that associates item-count to the presence of all of
the ^items, which are in turn associated to the proposed operators.
However, to be really correct, the conditions of the justification should
also include that no other operators are proposed. In addition, if chunking
is used, the chunks should encode that N and exactly N operators are
present, and that none are equal to any other.

I've attached a patch for my partial fix, but the rest probably also needs
to go in. Talking to Nate, it should be possible to make a fake preference
to encode that item-count is supported by the presence of all operators,
noneequal to any others, and no more.

**Attachment:** [patch](http://code.google.com/p/soar/issues/detail?id=56)

_Original issue: http://code.google.com/p/soar/issues/detail?id=56_

**Comment by mazina** [comment]
Soar does now add fake justifications for those preferences.  They even include fake identities.  We are considering adding specific conditions for each of the operators proposed.
