### ISSUE TITLE
deep operator elaborations not recognized as operator elaborations

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#6]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:02:59_

Description From Bob Marinier 2004-06-17 12:31:17 (-) [reply]
Consider these rules:

sp {propose
   (state <s> ^superstate nil)
-->
   (<s> ^operator <o> +)
}

sp {elaborate*operator
   (state <s> ^operator <o>)
-->
   (<o> ^foo <f>)
   (<f> ^bar <b>)
   (<b> ^test test)
}

Under o-support-mode 4, the second rule is supposed to get i-support since 
all 
the rule does is elaborate the operator.  However, Soar generates a 
warning:

WARNING:  operator elaborations mixed with operator applications get 
i_support 
in prod elaborate*operator

The problem is that the elaboration structure is not all directly connected 
to 
the operator, so the code which checks for this thinks the (<b> ^test test) 
is 
not an operator elaboration.

The problem appears to be in this if statement in p_node_left_addition in 
rete.c:

...
else if (current_agent(o_support_calculation_type) == 4 &&
         (rhs_value_is_reteloc(act->id)) &&
         (temp_tok->w->value == get_symbol_from_rete_loc(
                                 (byte)rhs_value_to_reteloc_levels_up(act-
>id),
                                 (byte)rhs_value_to_reteloc_field_num(act-
>id), 
                                 tok,
                                 w)))
        {
           op_elab = TRUE;
        }
...

Unfortunately, what this does is beyond me, so I don't know how to fix it.  
Stepping through the code, it is the final test in this if statement which 
is 
failing.  Specifically, the macros generate 0's for the first two 
arguments, 
and the returned pointer doesn't match temp_tok->w->value.  However, if I 
change the second argument to a 2, then it returns the correct pointer.  I 
don't know if this is a fluke or a hint at how to fix the problem.  Looking 
at 
the code for the macros and for get_symbol_from_rete_loc does not make 
anything 
clearer.

_Original issue: http://code.google.com/p/soar/issues/detail?id=3_

**Comment by mazina** [comment]
Related code has had a few changes over years.  Seems resolved.  
- Examples currently all return i-supported, which seems to be the correct behavior.
- o-support-4 mode is no longer an option and is just how it works now
- That old code seems to be missing the check of the attribute.  It's more robust now.
