### ISSUE TITLE
RHS arithmetic functions fail silently in Java debugger

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#65]
_From [joseph...@gmail.com](https://code.google.com/u/113587566993378695814/) on March 23, 2010 14:40:43_

RHS arithmetic operators and comparators fail if the constant operands
aren't numbers. More specifically, a rule like this:
```
sp {test
   (state <s> ^type state)
-->
   (<s> ^will-appear 1
        ^will-fail (+ 1 a)}
```
will fire, but only the (<s> ^will-appear 1) wme will be added to the
state. The (<s> ^will-fail ?) wme is simply ignored. 

An error is printed to console directly:

Error: non-number (a) passed to + function

This will appear in TestCLI, but not in the Java debugger. The error
reporting should be corrected so that the message appears in the Java debugger.

_Original issue: http://code.google.com/p/soar/issues/detail?id=64_

**Comment by mazina** [comment]
No longer an issue.  All of those functions now use output manager which will redirect to callbacks.
