### ISSUE TITLE
Possibly remove deep copy RHS function

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#7]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:04:55_

Description From Karen Coulter 2004-12-17 14:05:50 (-) [reply]
this functionality is either not general enough to be part of the supported
Soar
distribution, or needs Soar Consortium approval before being added.

-- "deepCopy" is a new RHS function that is deeply embedded in the kernel,
and is commented as a "HACK that should be doable through the external
kernel interface"    It creates a copy of a wme, makes a fake pref, and 
then
deallocates the wme, all in the matcher (create_instantiation) and also
adds references to objects.  I haven't investigated the cost of this code,
but it has potential to be significant.  I think this is the sort of change 
that should go to the Soar Consortium if SoarTech wants it to stay in the
distribution.  Certainly they can add it back in to their versions easily.

Nov 29:  ==>> should go thru Consortium for sure.  There may be other ways 
to
implement this, and alternatives should be evaluated.  Remove from kernel.

-- O_REJECTS_FIRST compiler directive added.  I think we should ask
SoarTech whether they still use this or whether it was for some 
experiments.
It doesn't cost anything since it's a compiler directive, but it is one 
more
option to support and understand.

Nov 29:  yep, we should take it out. check w/ SoarTech if even being used
regularly.

_Original issue: http://code.google.com/p/soar/issues/detail?id=4_

**Comment by mazina** [comment]
O_REJECTS_FIRST removed.   As for deep copy, despite being a hack and the fact Soar can't chunk properly over deep copies, too many people seem to use it to remove.  It has been made slightly less hacky.  No longer uses global.
