### ISSUE TITLE
wmes generated for constraint-failure impasse don't match documentation

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#75]
_From [marin...@gmail.com](https://code.google.com/u/110912605412702728125/) on June 02, 2010 13:28:47_

The Soar manual lists the wmes that are automatically created when
substates are generated. For the "choices" wme, it says:

"^choices  Either multiple (for tie and conflict impasses),
constraint-failure (for constraint-failure impasses), or none (for
no-change impasses)."

When a constraint-failure impasse is actually generated, "^choices none" is
created, which does not match the documentation. Thus, either the
implementation or the documentation is incorrect.

On the one hand, it seems unlikely that the documentation contains a typo,
since the special case for constraint-failure is explicitly called out.
This implies the code should be changed.

On the other hand, this is probably not a new issue (although we should
check the old decision procedure code to verify), and since
constraint-failure impasses cannot be resolved, it seems unlikely that
anyone would write code that depended on the specific value of this wme.
Thus, it makes no practical difference what the value is. Since it's easier
(and less risky) to change the manual, the implication is that the manual
should be changed. Laird agreed that this was reasonable, but if Jon thinks
changing the kernel is trivial, then we might as well "do it right".

_Original issue: http://code.google.com/p/soar/issues/detail?id=74_

**Comment by mazina** [comment]
Changed the manual to reflect what Soar does.
