### ISSUE TITLE
print s1 output changes depending on dc number

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#8]
_From [voigtjr@gmail.com](https://code.google.com/u/voigtjr@gmail.com/) on July 23, 2009 00:06:50_

Description From Bob Marinier 2005-07-13 09:06:13 (-) [reply]
1) Start the Java debugger
2) Change the state tab's command to "print s1"
3) Step.  Notice the format of the output of the command.
4) Step twice more.  Notice that, even though the contents of the output 
haven't
changed, the formatting has.
5) Step 4 times more.  The formatting has changed again.
6) Step 5 times more.  The formatting has changed again.  The formatting 
seems
to stabilize here.

I've confirmed the issue exists in TestCommandLineInterface as well.

This is probably an issue with how the formatting is generated internally 
in the
kernel.  If that's the case, then the issue should go away when we switch 
over
to using XML output for everything (at least, it'll fix it for the tree 
view). 
Given that, it may not be worth fixing this specific issue (unless it's 
really
easy).

_Original issue: http://code.google.com/p/soar/issues/detail?id=5_

**Comment by mazina** [comment]
Inconsistency in how Soar prints is a widespread issue that we've been slowly chipping away at for the last couple years.  I think what's being described here is that some unknown code, one of the many inconsistent peices of printing code, isn't isn't updating printed_output_column itself or isn't using one of the mechanisms that does it automatically.  Even if we fix the particular one causing what's described above, there will be others.  I'll be adding a more general issue for improving output handling generally that will subsume this.
