### ISSUE TITLE
Newlines in production doc strings no longer work

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#81]
_From [dave...@gmail.com](https://code.google.com/u/116926018696986116041/) on July 21, 2010 13:49:13_

If the doc string of a rule has a newline in it, it fails to parse:

p {test
"hello
there"
(state <s> ^superstate nil)
-->
(write hi)
}

This works in Soar 8.6.3.

_Original issue: http://code.google.com/p/soar/issues/detail?id=80_

**Comment by garfieldnate** [comment]
This has to be a pre-processing issue (a shell or something), because the reading of doc strings is basically "read until you get the next quote or the end of the document". I can even source productions with Japanese in the doc-string, and there's no problem.
