### ISSUE TITLE
Spawn Debugger doesn't work unless bin is on system path

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#82]
_From [dave...@gmail.com](https://code.google.com/u/116926018696986116041/) on July 29, 2010 13:19:01_

If an SML client calls Agent::SpawnDebugger(), but the Soar bin folder isn't on the system path, the debugger silently fails to start. I've only tested this on Windows.

I think one solution is to modify the debugger to use java.library.path to load libraries rather than relying on the system path. For this to work, because of lib dependencies, the debugger would have to manually load the libraries before any code in sml.jar is loaded:
        
        System.loadLibrary("ElementXML");
        System.loadLibrary(" SoarKernel SML");
        System.loadLibrary("Java_sml_ClientInterface");

Then Agent::SpawnDebugger() could easily add -Djava.library.path to the debugger startup command it builds.

_Original issue: http://code.google.com/p/soar/issues/detail?id=81_

**Comment by mazina** [comment]
Our scripts now do add that parameter as per Nate's suggestion (OSX Yosemite required it)
