### ISSUE TITLE
SpawnDebugger assumes that library path ends with a slash

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#83]
_From [dave...@gmail.com](https://code.google.com/u/116926018696986116041/) on July 29, 2010 13:46:51_

Agent::SpawnDebugger(int port, const char* pLibraryLocation) assumes that pLibraryLocation, if set, ends with a slash character and just tacks "bin" on the end of it. It should check for the slash and add it if its missing.

_Original issue: http://code.google.com/p/soar/issues/detail?id=82_

**Comment by mazina** [comment]
More robust file path search was added for spawndebugger, settings.soar and TclSoarLib
