### ISSUE TITLE
Inaccessibility of 'Application Data' folder prevents debugger from opening.

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#86]
_From [garfield...@gmail.com](https://code.google.com/u/101499011288491193842/) on December 24, 2010 15:05:23_

What steps will reproduce the problem? I was using this feature just fine for quite a while, and suddenly it stopped working. I guess the first thing to do would be:
1.On a windows machine, using java, run this code to find the relevant directory:
System.out.println(System.getProperty("user.home"));
On my machine is was c://users/username.
2. Go to that directory and see if a folder called "Application Data" exists. If it does, make it inaccessible somehow. I don't actually know how to do that, but on my Windows 7 machine it's inaccessible because it is a shortcut to somewhere, and when I click on it, it says "access denied".
3.Try the following Java code:
Kernel kernel = Kernel.CreateKernelInNewThread();
Agent agent = kernel.CreateAgent("testAgent");
agent.SpawnDebugger(Kernel.GetDefaultPort(),new SoarProperties().getPrefix());
System.out.println("worked"); What is the expected output? What do you see instead? I expect a debugger to popup, but none does. The string "worked" is still printed. What version of the product are you using? On what operating system? Soar 9.3.0, Windows 7 64 bit. Please provide any additional information below. The bug is not traceable with the Java debugger using the above code. But if you import Application from the debugger jar you can step through the code from here:
Application.main(new String[]{});
It turns out that the culprit is in the GetSettingsFilePath() function on line 65 of AppProperties:
   if (osName.toLowerCase().startsWith("windows"))
    {
      homeDir = new File(homeDir, "Application Data");

      homeDir = new File(homeDir, "SoarDebugger");
    }
There is no error checking done for the accessibility of the Application Data folder. I'm not sure what happens after java fails to open the file, but it never returns from it.

_Original issue: http://code.google.com/p/soar/issues/detail?id=85_

**Comment by garfieldnate** [comment]
I don't know how I ever messed my computer up so bad, but it had to do with migrating files between user accounts and losing access. It seems that this problem should have thrown an IO error in `java.util.Properties.load(InputStream)`. We could check permissions using `FilePermission` and `AccessController`.
