### ISSUE TITLE
incorrect parsing of dot notation and numeric attributes

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#87]
_From [joseph...@gmail.com](https://code.google.com/u/113587566993378695814/) on January 11, 2011 12:20:07_

When Soar sources this rule:

sp {test1
   (state <s> ^a.1234 <a>)
-->
}

it is reinterpreted as

sp {test1
   (state <s> ^a 0.1234 ^a <a>)
    -->
    
}

which seems wrong to me. If the sourced rule is changed to

sp {test1
   (state <s> ^a.|1234| <a>)
-->
}

then the result is as expected.

**Attachment:** [testcase.soar](http://code.google.com/p/soar/issues/detail?id=86)

_Original issue: http://code.google.com/p/soar/issues/detail?id=86_

**Comment by garfieldnate** [comment]
Duplicate with #136.

**Comment by mazina** [comment]
Fixed in other issue.
