### ISSUE TITLE
Memory leak reported after chunking with save-backtraces enabled

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#88]
_From [nate.der...@gmail.com](https://code.google.com/u/105203827464787627414/) on January 25, 2011 15:30:25_

What steps will reproduce the problem? 1. Enable save-backtraces
2. Create a chunk/justification
(I attached an agent that does this: source, run, quit) What is the expected output? What do you see instead? TestCLI will report lots of memory leaks on exit. While not really important (see below), this could derail hunting down real memory leaks and/or sidetrack debugging.

The save-backtraces command stores backtrace information when creating chunks/justifications. This process uses existing functions to copy condition lists and related structures, and thus adds reference counts all around. On quit, these are not cleaned up properly, which triggers the memory leak report.

There is no "clear" functionality with save-backtraces, so this memory just monotonically increases till Soar exits. If we accept this as the purpose of the command, this is a memory leak only in the sense that it doesn't explicitly give back memory at the end of execution.

**Attachment:** [leak.soar](http://code.google.com/p/soar/issues/detail?id=87)

_Original issue: http://code.google.com/p/soar/issues/detail?id=87_

**Comment by mazina** [comment]
Obsolete
