### ISSUE TITLE
Rule parser should warn if action asserts a reject preference for an unbound variable

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#90]
_From [nate.der...@gmail.com](https://code.google.com/u/105203827464787627414/) on June 10, 2011 13:04:06_

Source the attached file. It will automatically output the time of 5 sequential 10k decision runs. The times get quadratically slower. Now, uncomment the second condition in apply*next (^foo <bar>), problem fixed. This relates to what could be a common mistake for agent developers, which will have performance consequences (not to mention intended outcomes).

**Attachment:** [slow.soar](http://code.google.com/p/soar/issues/detail?id=89)

_Original issue: http://code.google.com/p/soar/issues/detail?id=89_

**Comment by mazina** [comment]
This could be done in the re-orderer.  I don't think the parser can tell what's an unbound variable.
