### ISSUE TITLE
smem --init sometimes clears output from previous commands

### ISSUE THREAD

**Issue by ghost** [SoarGroup/Soar#91]
_From [marin...@gmail.com](https://code.google.com/u/110912605412702728125/) on June 13, 2011 09:00:13_

What steps will reproduce the problem? 1. source a file containing this:

time run 5
smem --init
time run 5
smem --init
time run 5
smem --init
time run 5
smem --init What is the expected output? What do you see instead? I expect to see 3 different timing results. Instead all I see is the result of the source command. It appears that the smem --init is somehow clearing the results before they get printed? Interestingly, the behavior is a bit more complciated. If I do something like this:

time run 5
stats
p s1
smem --init

Everything except the time run 5 results is shown. Anyway, something funny is going on here. And no, I'm not sure that it's specific to smem --init.

_Original issue: http://code.google.com/p/soar/issues/detail?id=90_

**Comment by mazina** [comment]
No longer seems to be an issue.
